import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

INSTRU_SKILL = r"""
,

  instru: {
    id: 'instru',
    name: 'Thiết bị đo lường',
    icon: '📡',
    color: '#0891b2',
    renderMode: 'van',
    categories: [
      { id:'temp',  name:'Nhiệt độ',  color:'#dc2626' },
      { id:'pres',  name:'Áp suất',   color:'#0891b2' },
      { id:'level', name:'Mức',       color:'#047857' },
      { id:'flow',  name:'Lưu lượng', color:'#7c3aed' },
      { id:'ana',   name:'Phân tích', color:'#d97706' },
    ],

    concepts: {
      pt100:    { title:'RTD PT100 – Điện trở nhiệt', e:'🌡️',
        body:'PT100: Điện trở Platinum tại 0°C = 100 Ω.\nCông thức: RT = R₀[1 + α(T − T₀)]\nα = 0.00392 Ω/Ω·°C (tiêu chuẩn IEC 60751)\nDải đo: −200 °C đến +850 °C\nDo điện trở dây dẫn gây sai số → dùng 3-wire hoặc 4-wire để bù.',
        note:'PT100 phổ biến nhất tại NM Đạm Cà Mau. Hãng: Rosemount, E+H, Yokogawa.' },
      seebeck:  { title:'Thermocouple – Hiệu ứng Seebeck', e:'⚡',
        body:'Khi 2 kim loại khác nhau hàn nối tại 1 điểm, sự chênh lệch nhiệt độ tạo ra EMF:\nV = S × (T − T_ref)\nS: Hệ số Seebeck (μV/°C), phụ thuộc loại cặp nhiệt.\nType K (Chromel-Alumel): S ≈ 41 μV/°C, −200~+1260 °C – phổ biến nhất.\nType J (Fe-Constantan): S ≈ 51 μV/°C, 0~+750 °C.',
        note:'Thermocouple đo T cao hơn RTD, dải rộng hơn nhưng kém chính xác hơn.' },
      cjc:      { title:'CJC – Cold Junction Compensation', e:'🔧',
        body:'Thermocouple đo hiệu nhiệt độ giữa 2 đầu nối.\nĐầu nối tại transmitter/đồng hồ = "Cold Junction" phải được đo nhiệt độ môi trường.\nTransmitter tự động bù trừ T_ref (CJC) để tính T_process chính xác.\nMạch bù: cầu Wheatstone hoặc cảm biến nhiệt tích hợp.',
        note:'Thiếu CJC → sai số lớn, đặc biệt khi nhiệt độ môi trường thay đổi.' },
      thermowell: { title:'Thermowell – Ống bảo vệ đầu đo', e:'🛡️',
        body:'Thermowell: ống kim loại bảo vệ đầu cảm biến (RTD/Thermocouple) khỏi áp suất, ăn mòn, dòng chảy.\nVật liệu: Carbon steel, SS316, Hastelloy.\nKiểu lắp: Threaded, Flanged, Weld-in.\nThông số quan trọng: chiều dài nhúng (immersion length), đường kính, vật liệu.\nLỗi thường gặp: thermowell rung cộng hưởng (Strouhal resonance) gây gãy.',
        note:'Tất cả cặp nhiệt/RTD tiếp xúc lưu chất nguy hiểm đều phải qua thermowell.' },
      tx_4_20:  { title:'Transmitter – Tín hiệu 4-20mA', e:'📶',
        body:'Transmitter chuyển đổi tín hiệu cảm biến (mV, Ω, pF) thành dòng điện 4-20mA.\n4mA = 0% (LRV), 20mA = 100% (URV).\n< 3.6mA = đứt dây (wire-break fault).\nSmart Transmitter: thêm giao thức HART (digital superimposed) hoặc FF (Foundation Fieldbus).\nHART: 2 chiều, 1200 bps, cho phép cấu hình từ xa qua DCS/PRM.',
        note:'Tiêu chuẩn 4-20mA + HART là tiêu chuẩn nhà máy Đạm Cà Mau.' },
      dp_cell:  { title:'DP Cell – Cảm biến vi sai áp', e:'⚡',
        body:'DP Transmitter đo hiệu áp giữa 2 điểm: ΔP = P_high − P_low.\nCấu tạo: 2 buồng (H/L) ngăn cách bởi màng cảm biến.\nNguyên lý điện dung: màng dịch chuyển → C thay đổi → ΔP tính được.\nDải đo: 0.1 mbar đến 40 bar ΔP.\nỨng dụng: đo lưu lượng (qua Orifice/Venturi), đo mức (hydrostatic), đo áp suất lọc.',
        note:'Rosemount 3051, E+H Deltabar, Yokogawa EJA phổ biến tại NM.' },
      manifold: { title:'Valve Manifold – Khối van cô lập', e:'🔧',
        body:'Manifold: cụm van compact nối DP transmitter với đường process.\nLoại:\n• 2-valve: Isolation (H) + Isolation (L) – dùng với pressure/level TX\n• 3-valve: 2 Isolation + 1 Equalization – DP transmitter\n• 5-valve: 2 Isolation + 2 Blowdown + 1 Equalization – DP quan trọng\nQuy trình hiệu chuẩn (zero DP TX): Mở equalizer → đóng 2 isolation → zero.',
        note:'Mọi DP transmitter tại NM đều có manifold để cô lập và hiệu chuẩn online.' },
      buoyancy: { title:'Buoyancy – Lực đẩy Archimedes', e:'🌊',
        body:'Lực đẩy = trọng lượng chất lỏng bị chiếm chỗ:\nFb = ρ × g × V = ρ × g × A × h\nρ: mật độ chất lỏng (kg/m³)\nA: diện tích tiết diện ngang phao/displacer\nh: chiều cao nhúng trong chất lỏng\nKhi mức thay đổi → Fb thay đổi → lực tác dụng lên đầu đo thay đổi.',
        note:'Float: phao nổi theo mức. Displacer: chìm hoàn toàn, đo biến thiên lực.' },
      cap_sens: { title:'Capacitance Level – Điện dung mức', e:'🔋',
        body:'Điện dung giữa que đo và thành bình:\nC = ε × A / d\nKhi mức thay đổi → hằng số điện môi ε thay đổi → C thay đổi.\nLỏng dẫn điện: dùng que đo có vỏ bọc cách điện (lỏng là 1 bản tụ)\nLỏng không dẫn điện: dùng que đo trần (que đo là 1 bản tụ)\nBụi/rắn: cũng áp dụng được.\nNhược: ảnh hưởng bởi nhiệt độ và thành phần chất lỏng.',
        note:'Capacitance level phổ biến trong bình chứa hóa chất và silo hạt.' },
      ultrasonic_l: { title:'Ultrasonic Level – Đo mức siêu âm', e:'📡',
        body:'Phát xung siêu âm từ đỉnh bình → phản xạ từ bề mặt chất lỏng → nhận.\nDistance = (SoS × t_delay) / 2\nSoS ≈ 343 m/s (không khí 20°C).\nTần số: 15...200 kHz.\nKhoảng trống (deadband): vùng ngay dưới transducer không đo được (~0.3m).\nNhược điểm: bị ảnh hưởng bởi nhiệt độ, hơi, bụi, sóng mặt.',
        note:'Ultrasonic level dùng phổ biến cho bể chứa hở, không tiếp xúc lưu chất.' },
      radar_fmcw: { title:'Radar FMCW Level – Đo mức radar', e:'📡',
        body:'FMCW (Frequency Modulated Continuous Wave):\n• Phát sóng vi ba liên tục, tần số biến thiên tuyến tính (sweep)\n• Sóng phản xạ từ mặt chất lỏng về có trễ thời gian t\n• Vì tần số thay đổi tuyến tính → Δf tương ứng với t → tính distance\nd = (Δf × c) / (2 × sweep_rate)\nTần số: 6 GHz (bề mặt mấp mô) hoặc 26 GHz (chính xác cao).\nƯu: không bị ảnh hưởng bởi hơi nước, bụi, thay đổi nhiệt độ.',
        note:'Radar FMCW dùng cho bình áp lực, chất lỏng hóa chất, độ chính xác ±1 mm.' },
      orifice:  { title:'Orifice Plate – Tấm lỗ đo lưu lượng', e:'⭕',
        body:'Dựa trên phương trình liên tục + Bernoulli:\nQ = A×v = const → A₁v₁ = A₂v₂\nKhi dòng đi qua lỗ thu hẹp → v tăng → P giảm → ΔP tỷ lệ với v²\nQ ∝ √ΔP\nQ = Cd × A_orifice × √(2ΔP/ρ)\nCd: hệ số xả lưu (Cd ≈ 0.6 cho orifice tấm phẳng).\nOrifice đơn giản, rẻ, nhưng tổn thất áp lớn, dễ bị cặn bám.',
        note:'Orifice + DP Transmitter là phương pháp đo lưu lượng phổ biến nhất tại NM.' },
      vortex_s: { title:'Vortex Flowmeter – Dòng xoáy Karman', e:'🌀',
        body:'Khi dòng chảy qua vật cản (bluff body), sinh dòng xoáy Karman xen kẽ 2 bên.\nTần số xoáy tỷ lệ với vận tốc dòng:\nf = S × v / d\nS ≈ 0.17 (Strouhal number)\nQ = f × d / S × A\nĐầu đo: Piezoelectric hoặc capacitive sensor đo dao động áp/lực.\nYêu cầu Reynolds: Re > 10000 (không đo lưu chất nhớt).',
        note:'Vortex flowmeter dùng cho hơi nước, khí, chất lỏng sạch tại NM.' },
      magflow:  { title:'Magnetic Flowmeter – Đo điện từ Faraday', e:'⚡',
        body:'Dựa trên Định luật Faraday: E = B × L × v\nE: EMF cảm ứng (V)\nB: từ trường (T)\nL: khoảng cách 2 điện cực (m)\nv: vận tốc dòng chảy (m/s)\nDòng chảy → cắt từ trường → EMF → đo bằng điện cực → tính Q.\nYêu cầu: chất lỏng DẪN ĐIỆN (độ dẫn ≥ 5 μS/cm).\nƯu: không tổn thất áp, không bộ phận chuyển động.',
        note:'Magnetic flowmeter dùng cho nước, dung dịch hóa chất, không dùng cho khí.' },
      coriolis:{ title:'Coriolis Mass Flowmeter – Đo khối lượng trực tiếp', e:'🔄',
        body:'Nguyên lý: Ống rung → dòng chảy → lực Coriolis → ống xoắn lệch pha.\nMass flow ∝ ΔT (time shift giữa 2 điểm đo)\nDensity ∝ 1/f² (tần số rung phụ thuộc mật độ)\nĐầu ra: Mass flow + Density + Temperature (multi-variable).\nChính xác: ±0.1% mass flow, ±0.5 kg/m³ density.\nHạn chế: đắt, áp suất giảm, khó dùng với khí ở áp thấp.',
        note:'Coriolis dùng cho đo khối lượng trực tiếp NH₃, CO₂ lỏng, hóa chất tại NM.' },
      ms_gc:   { title:'Mass Spectrometer & GC – Phân tích thành phần khí', e:'🔬',
        body:'Mass Spectrometer (MS):\n• Ion hóa phân tử → tách theo m/z → đo dòng ion\n• Phân tích đồng thời nhiều cấu tử: CH4/CO/CO2/H2/N2/NH3\n• 10-point online sampling tại NM Đạm Cà Mau\nGas Chromatograph (GC):\n• Tách cấu tử qua cột GC (thời gian lưu giữ)\n• GC1000 Mark II (Yokogawa) tại NM: H2/O2/CO2/CH4/NH3\n• Chu kỳ phân tích: 2-10 phút/chu kỳ',
        note:'MS nhanh hơn GC nhưng GC phân tích được nhiều loại hơn, chính xác hơn.' },
      cems_ana: { title:'CEMS – Continuous Emissions Monitoring', e:'🏭',
        body:'Hệ thống giám sát phát thải liên tục:\nChỉ tiêu: NOx, CO, O2 (bắt buộc theo quy định môi trường)\nModel tại NM: Rosemount X-Stream XEFD (Emerson)\nVị trí: 01 tại Boiler + 01 tại Reforming\nNguyên lý đo:\n• NOx: Chemiluminescence hoặc NDIR\n• CO: NDIR (Non-Dispersive Infrared)\n• O2: Paramagnetic hoặc Electrochemical\nEMS: giám sát thêm NH3, áp suất, tiếng ồn, độ ẩm, gió, bụi.',
        note:'CEMS phải báo cáo định kỳ cho cơ quan môi trường theo quy định nhà nước.' },
      ph_cond: { title:'pH & Conductivity Analyzer', e:'💧',
        body:'pH:\n• Đo hoạt độ ion H⁺: pH = −log[H⁺]\n• Điện cực thủy tinh (glass electrode) tạo EMF tỷ lệ với pH\n• Cần chuẩn hóa 2 điểm (pH 4 + pH 7 hoặc pH 7 + pH 10)\n• 15 máy tại NM (Yokogawa): DEMI, Cooling, Boiler, Fresh water\nConductivity:\n• Đo khả năng dẫn điện (μS/cm hoặc mS/cm)\n• Phản ánh tổng lượng ion trong nước\n• 24 máy tại NM (Yokogawa): kiểm soát chất lượng nước',
        note:'pH và conductivity quan trọng để kiểm soát ăn mòn trong lò hơi và làm mát.' },
      gasdet:  { title:'Gas Detector – Đầu dò khí F&G', e:'⚠️',
        body:'Phát hiện khí độc và khí cháy nổ trong môi trường:\nLoại tại NM: NH₃ (88 đầu), CO (4 đầu), Flammable (15 đầu) → tổng ~108 đầu\nNguyên lý:\n• Catalytic bead: đốt cháy khí → nhiệt → điện trở thay đổi (khí cháy)\n• Electrochemical: phản ứng điện hóa (NH₃, CO, H₂S)\n• NDIR: hấp thụ hồng ngoại (CH₄, CO)\nHãng: Honeywell XCD Series\nNgưỡng: cảnh báo ở 10% LEL (khí cháy) hoặc TLV-TWA (khí độc).',
        note:'108 đầu dò khí F&G thuộc hệ thống FGS/ESD tại NM Đạm Cà Mau.' },
    },

    data: [
      /* ─── NHIỆT ĐỘ ─── */
      { id:0, stt:'T1', cat:'temp', name:'RTD – Resistance Temperature Detector (PT100)', sub:'PT100 · α=0.00392 · 3-wire/4-wire · Rosemount/E+H/Yokogawa',
        cells:[
          { l:'Nguyên lý',       v:'Điện trở Pt thay đổi tuyến tính theo nhiệt độ' },
          { l:'Công thức',       v:'RT = R₀ × [1 + α(T − T₀)], R₀=100Ω, α=0.00392' },
          { l:'Kết nối dây',     c:[{t:'3-wire (bù 1 dây)',k:'pt100'},{t:'4-wire (bù 2 dây)',k:'pt100'}] },
          { l:'Hãng tại NM',     c:[{t:'Rosemount',k:'pt100'},{t:'E+H',k:'pt100'},{t:'Yokogawa',k:'pt100'}] },
          { l:'Tín hiệu ra',     c:[{t:'4-20mA + HART',k:'tx_4_20'},{t:'FF Foundation Fieldbus',k:'tx_4_20'}] },
        ],
        goal:'Đo nhiệt độ bằng điện trở Platinum thay đổi theo nhiệt độ. Chính xác hơn thermocouple trong dải −50 °C đến +600 °C. Phổ biến tại NM Đạm Cà Mau.',
        detail:'Nguyên lý: Điện trở Platinum tăng tuyến tính với nhiệt độ.\nCông thức: RT = R₀[1 + α(T − T₀)] với R₀=100Ω (PT100), α=0.00392 Ω/Ω·°C.\n3-wire RTD: bù 1 điện trở dây → giảm sai số đường dây.\n4-wire RTD: bù 2 điện trở → chính xác nhất → dùng cho hiệu chuẩn.',
        equip:'Rosemount 0065, 0085 (NM)\nE+H TR10, TR30\nYokogawa (DEMI, Cooling)',
        params:'Dải: −200 °C đến +850 °C\nR₀=100Ω, α=0.00392\n3-wire/4-wire bù điện trở dây' },

      { id:1, stt:'T2', cat:'temp', name:'Thermocouple – Cặp nhiệt điện', sub:'Seebeck V=(T−Tref)×S · Type K/J · Dải rộng · CJC',
        cells:[
          { l:'Hiệu ứng Seebeck',c:[{t:'V=(T−Tref)×S',k:'seebeck'},{t:'S: hệ số Seebeck μV/°C',k:'seebeck'}] },
          { l:'Loại phổ biến',   c:[{t:'Type K (-200~+1260°C)',k:'seebeck'},{t:'Type J (0~+750°C)',k:'seebeck'},{t:'Type E/N/R/S/T',k:'seebeck'}] },
          { l:'Bù đầu nối lạnh', c:[{t:'Cold Junction Comp. (CJC)',k:'cjc'}], w:1 },
          { l:'Tín hiệu ra',     v:'mV (nhỏ) → cần khuếch đại trong transmitter' },
        ],
        goal:'Đo nhiệt độ cao (đến 1600°C) bằng hiệu ứng Seebeck. Dải rộng hơn RTD, giá rẻ hơn, nhưng kém chính xác hơn. Cần bù đầu lạnh (CJC).',
        detail:'Nguyên lý Seebeck: 2 kim loại dị chất hàn nối tạo ra EMF khi có ΔT.\nV_meter = S × (T_hot − T_ref)\nType K: Chromel-Alumel, S≈41μV/°C, −200~+1260°C, phổ biến nhất.\nType J: Iron-Constantan, S≈51μV/°C, 0~+750°C, dùng trong môi trường oxy hóa.\nCJC: transmitter đo nhiệt độ đầu nối lạnh và bù tự động.',
        equip:'Rosemount 0065 (thermocouple)\nE+H TC series\nType K cho lò hơi, reformer',
        params:'Type K: −200~+1260°C\nType J: 0~+750°C\nCJC bắt buộc trong transmitter' },

      { id:2, stt:'T3', cat:'temp', name:'Temperature Transmitter & Thermowell', sub:'4-20mA · Smart HART · Thermowell bảo vệ · Rosemount/E+H',
        cells:[
          { l:'Transmitter',    c:[{t:'4-20mA + HART',k:'tx_4_20'},{t:'Foundation Fieldbus',k:'tx_4_20'},{t:'ISA100 Wireless',k:'tx_4_20'}] },
          { l:'Thermowell',     c:[{t:'Bảo vệ áp & ăn mòn',k:'thermowell'},{t:'Vật liệu SS316/Hastelloy',k:'thermowell'}], w:1 },
          { l:'Kiểu lắp TW',   v:'Threaded, Flanged, Weld-in' },
          { l:'Rủi ro Thermowell', v:'Rung cộng hưởng Strouhal → gãy TW' },
        ],
        goal:'Chuyển đổi tín hiệu RTD/TC thành 4-20mA HART để truyền về DCS. Thermowell bảo vệ đầu đo khỏi áp suất và ăn mòn. Rosemount 644/848T tại NM.',
        detail:'Temperature Transmitter:\n• Đầu vào: RTD 2/3/4-wire, Thermocouple, Ohm\n• Đầu ra: 4-20mA + HART 5/6/7\n• Smart: tự chẩn đoán, cấu hình từ xa qua DCS/PRM\n• Rosemount 644: phổ biến nhất NM Đạm Cà Mau\nThermowell:\n• Bảo vệ cảm biến khỏi áp suất process, ăn mòn, lưu chất nguy hiểm\n• Chiều dài nhúng: U-length phụ thuộc đường kính ống và vận tốc dòng\n• Kiểm tra rung cộng hưởng: Wake Frequency Calculation (ASME PTC 19.3)',
        equip:'Rosemount 644 TX (NM)\nE+H iTEMP TMT82\nThermowell SS316, Hastelloy C276',
        params:'Input: RTD PT100/PT1000, TC K/J/E\nOutput: 4-20mA + HART\nThermowell: ASME PTC 19.3 check' },

      /* ─── ÁP SUẤT ─── */
      { id:3, stt:'P1', cat:'pres', name:'Pressure Gauge – Đồng hồ đo áp cơ học', sub:'Bourdon tube · Diaphragm · Bellows · Đọc tại chỗ',
        cells:[
          { l:'Phần tử đo',     c:[{t:'Bourdon tube (xoắn/C-type)',k:'dp_cell'},{t:'Diaphragm',k:'dp_cell'},{t:'Bellows/Capsule',k:'dp_cell'}] },
          { l:'Nguyên lý',      v:'Áp suất → biến dạng phần tử đàn hồi → quay kim' },
          { l:'Ứng dụng',       v:'Đọc tại chỗ, không cần tín hiệu điện' },
          { l:'Loại đặc biệt',  v:'Glycerin-filled (chống rung), SS diaphragm (ăn mòn)' },
        ],
        goal:'Đo và hiển thị áp suất trực tiếp tại chỗ. Không cần nguồn điện. Dùng để kiểm tra nhanh, giám sát tại hiện trường.',
        detail:'Nguyên lý: Áp suất process → biến dạng phần tử đàn hồi → thanh truyền → quay kim.\nBourdon tube: ống cong, áp suất làm ống thẳng ra → phổ biến nhất\nDiaphragm capsule: màng mỏng, nhạy cảm với áp thấp\nBellows: nhiều lớp màng, dùng cho áp rất thấp\nBảo vệ: Glycerin-filled giảm rung, SS seal cho hóa chất\nANSI B40.100: Tiêu chuẩn áp kế công nghiệp.',
        equip:'Wika, Ashcroft, Bourdon\nGlycerine-filled, SS wetted parts\nLắp thẳng đứng hoặc nghiêng',
        params:'Dải: 0-1 bar đến 0-700 bar\nĐộ chính xác: 1-2% FS\nKhông cần nguồn điện' },

      { id:4, stt:'P2', cat:'pres', name:'Pressure Transmitter – Cảm biến áp điện tử', sub:'Capacitance · 4-20mA HART · Gauge/Absolute/Differential · Rosemount 3051',
        cells:[
          { l:'Nguyên lý điện tử', c:[{t:'Differential Capacitance',k:'dp_cell'},{t:'Piezoresistive',k:'dp_cell'}] },
          { l:'Loại đo',          c:[{t:'Gauge (so với khí quyển)'},{t:'Absolute (so với chân không)'},{t:'Differential ΔP = P₁−P₂',k:'dp_cell'}] },
          { l:'Tín hiệu ra',      c:[{t:'4-20mA + HART',k:'tx_4_20'},{t:'FF H1',k:'tx_4_20'}] },
          { l:'Hãng tại NM',      c:[{t:'Rosemount 3051',k:'dp_cell'},{t:'E+H Cerabar',k:'dp_cell'},{t:'Yokogawa EJA',k:'dp_cell'}] },
        ],
        goal:'Đo áp suất chính xác và truyền tín hiệu 4-20mA về DCS. Rosemount 3051 là thiết bị phổ biến nhất tại NM cho đo áp suất.',
        detail:'Nguyên lý: Áp suất → biến dạng màng cảm biến → thay đổi điện dung (Differential Capacitance).\nC_high và C_low thay đổi đối xứng → mạch đo tính P từ ΔC/ΣC.\nLoại:\n• Gauge: P so với áp khí quyển (Pg = P_abs − P_atm)\n• Absolute: P so với chân không (dùng cho cột chưng cất)\n• Differential: P₁ − P₂ (lưu lượng, lọc, mức)\nSmart HART: tự chẩn đoán, đặt zero/span từ xa, cảnh báo độ lệch.',
        equip:'Rosemount 3051C, 3051T (NM)\nE+H Cerabar M/S\nYokogawa EJA110/EJA210',
        params:'Dải: 0.1 mbar đến 700 bar\nĐộ chính xác: ±0.04% to ±0.1%\nOutput: 4-20mA + HART' },

      { id:5, stt:'P3', cat:'pres', name:'DP Transmitter & Valve Manifold', sub:'ΔP=P₁−P₂ · 2/3/5-valve manifold · Hiệu chuẩn online · DP Level/Flow',
        cells:[
          { l:'DP Transmitter',  c:[{t:'Rosemount 3051CD',k:'dp_cell'},{t:'E+H Deltabar',k:'dp_cell'},{t:'Yokogawa EJA110',k:'dp_cell'}] },
          { l:'Valve Manifold',  c:[{t:'3-valve (Iso×2 + Equal)',k:'manifold'},{t:'5-valve (ISO×2+BLW×2+EQ)',k:'manifold'}] },
          { l:'Quy trình zero',  c:[{t:'Mở Equalizer → đóng Iso → Zero TX',k:'manifold'}], w:1 },
          { l:'Ứng dụng DP',     v:'Đo lưu lượng, mức, lọc, áp suất vi sai' },
        ],
        goal:'DP Transmitter đo vi sai áp suất cho lưu lượng và mức. Manifold cho phép cô lập và hiệu chuẩn zero trực tiếp trên dây tại hiện trường.',
        detail:'DP Transmitter: đo ΔP = P_H − P_L với ΔP ≥ 0.1 mbar.\nỨng dụng:\n• Lưu lượng: qua orifice/venturi, Q ∝ √ΔP\n• Mức: ΔP = ρ×g×h (hydrostatic)\n• Lọc: ΔP = mức độ tắc nghẽn\nValve Manifold:\n• 2-valve: 2×Isolation (dùng với pressure TX)\n• 3-valve: 2×Iso + 1×Equalize (DP TX)\n• 5-valve: 2×Iso + 2×Blowdown + 1×Equalize\nQuy trình zero DP TX: Mở equalize → đóng 2 isolation → adjust zero → đóng equalize → mở isolation.',
        equip:'Rosemount 3051CD (ΔP)\n3-valve manifold (mọi DP TX)\n5-valve manifold (quan trọng)',
        params:'ΔP range: 0.1 mbar đến 40 bar\n3-valve: Iso×2 + Equal×1\n5-valve: Iso×2 + BLW×2 + EQ×1' },

      /* ─── MỨC ─── */
      { id:6, stt:'L1', cat:'level', name:'Level Gauge – Quan sát mức trực quan', sub:'Sight glass · Magnetic level gauge · Không cần điện · Kiểm tra tại chỗ',
        cells:[
          { l:'Loại',    c:[{t:'Tubular sight glass'},{t:'Flat glass gauge'},{t:'Magnetic level gauge (MLG)'}] },
          { l:'Nguyên lý', v:'Bình thông nhau: mức trong gauge = mức trong bình' },
          { l:'MLG',     v:'Phao từ + thanh hiển thị 2 màu: đỏ/trắng' },
          { l:'Ứng dụng',v:'Dùng song song với TX để kiểm tra và backup' },
        ],
        goal:'Quan sát mức trực tiếp bằng mắt không cần nguồn điện. Magnetic Level Gauge (MLG) hiển thị mức qua phao từ và thanh lật 2 màu.',
        detail:'Level Gauge kiểu bình thông nhau: mức trong ống thủy tinh = mức trong bình (Pascal).\nTubular sight glass: ống thủy tinh đơn giản, dùng áp thấp, nhiệt độ thấp.\nFlat glass gauge: kính phẳng chịu áp, nhìn thấy mức qua rãnh phản xạ.\nMagnetic Level Gauge (MLG): Phao từ tính nổi theo mức → từ trường xoay các tấm bi-color 2 mặt (đỏ = dầu, trắng = khí) → đọc mức từ xa. Không tiếp xúc.\nSwitches: lắp thêm tiếp điểm reed switch báo Hi/Lo về DCS.',
        equip:'Clark-Reliance, Jerguson MLG\nKlinger, McDaniel sight glass\nReed switch liên kết DCS',
        params:'Áp làm việc: đến PN250\nNhiệt độ: đến +350°C (MLG)\nKhông cần nguồn điện' },

      { id:7, stt:'L2', cat:'level', name:'DP Level – Đo mức bằng áp suất thủy tĩnh', sub:'ΔP=ρgh · Dry leg · Wet leg · Compensated leg · Rosemount 3051',
        cells:[
          { l:'Nguyên lý',       v:'ΔP = ρ × g × h → h = ΔP / (ρ × g)' },
          { l:'Bình hở (Dry)',   c:[{t:'HP = liquid pressure'},{t:'LP = atmosphere'}] },
          { l:'Bình kín (Wet)',  c:[{t:'Compensated leg (hơi)',k:'dp_cell'},{t:'Suppression/Elevation',k:'dp_cell'}] },
          { l:'TX DP',           c:[{t:'Rosemount 3051L',k:'dp_cell'},{t:'E+H Deltabar',k:'dp_cell'}] },
        ],
        goal:'Phương pháp đo mức phổ biến nhất tại NM. DP TX đo áp suất thủy tĩnh tỷ lệ với chiều cao chất lỏng.',
        detail:'Nguyên lý: ΔP = ρ×g×h → TX đo ΔP → tính h khi biết ρ.\nBình hở (Dry leg):\n• H-port: áp suất chất lỏng tại đáy bình\n• L-port: thông khí quyển (hoặc bình kín không có chất lỏng leg)\nBình kín (Wet leg / Compensated leg):\n• Bình chứa hơi nước → L-leg đầy nước ngưng → cần tính suppression\n• L-port = áp hơi + ρ_water × g × L_leg → bù offset TX\nElevation: khi TX đặt cao hơn datum → H-port bù negative\nSuppression: khi TX đặt thấp hơn → bù positive.',
        equip:'Rosemount 3051L, 3051CD\nE+H Deltabar FMD77/78\n3-valve hoặc 5-valve manifold',
        params:'h = ΔP/(ρ×g)\nBình kín: cần tính leg compensation\nSuppress/Elevate khi TX offset' },

      { id:8, stt:'L3', cat:'level', name:'Buoyancy Level – Phao & Displacer', sub:'Fbuoyant=ρgAh · Float loại 1 · Displacer loại 2 · Fisher/Magnetrol',
        cells:[
          { l:'Lực đẩy Archimedes', c:[{t:'Fb = ρ×g×A×h',k:'buoyancy'}] },
          { l:'Float (phao nổi)',   v:'Phao nhẹ nổi trên mặt → theo mức → truyền cơ học' },
          { l:'Displacer (chìm)',   v:'Vật nặng luôn chìm → đo biến thiên lực nổi' },
          { l:'Ứng dụng',          v:'Displacer: bình có 2 pha (dầu/nước) hoặc interface' },
        ],
        goal:'Đo mức bằng lực đẩy Archimedes. Float theo dõi bề mặt chất lỏng. Displacer đo biến thiên lực nổi để xác định mức hoặc giao diện 2 pha.',
        detail:'Nguyên lý: Fb = ρ×g×V = ρ×g×A×h\nFloat (phao nổi): Phao nhẹ nổi hoàn toàn trên mặt lỏng, kết nối qua cần hoặc dây cáp với cảm biến vị trí. Dùng cho bình hở, không áp suất.\nDisplacer: Hình trụ kim loại nặng luôn chìm hoàn toàn. Khi mức tăng → lực nổi tăng → biến lực thay đổi → transmitter đo. Dùng trong bình áp lực.\nInterface: Displacer tại giao diện dầu-nước → đo tỷ lệ 2 pha.',
        equip:'Fisher L2 (displacer, local)\nMagnetrol E3 (displacer tx)\nGemini interface float',
        params:'Fb = ρ×g×A×h\nDisplacer: luôn chìm (ρ_dis >> ρ_fluid)\nInterface: ρ₁ ≤ ρ_dis ≤ ρ₂' },

      { id:9, stt:'L4', cat:'level', name:'Capacitance Level – Đo mức điện dung', sub:'C=εA/d · Dẫn điện & Không dẫn điện · Silo · Hóa chất',
        cells:[
          { l:'Nguyên lý',            c:[{t:'C = ε×A/d → ε thay đổi theo mức',k:'cap_sens'}] },
          { l:'Lỏng dẫn điện',        c:[{t:'Que đo có vỏ bọc cách điện',k:'cap_sens'}] },
          { l:'Lỏng không dẫn điện', c:[{t:'Que đo trần, lỏng là điện môi',k:'cap_sens'}] },
          { l:'Ứng dụng',             v:'Hóa chất, axit, dung môi, bột rắn, silo' },
        ],
        goal:'Đo mức không chuyển động bằng nguyên lý điện dung. Không bị ảnh hưởng bởi bọt, hơi. Phù hợp cho hóa chất, dung môi, vật liệu rắn.',
        detail:'Nguyên lý: C = ε₀ × εᵣ × A / d\nKhi mức thay đổi → phần que đo ngập trong chất lỏng thay đổi → ε_eff thay đổi → C thay đổi.\nLỏng dẫn điện (e.g. nước axit): Vỏ PTFE cách điện que đo; lỏng và thành bình = 2 bản tụ → C ~ ε_PTFE × A_ngap.\nLỏng không dẫn điện (e.g. dầu, dung môi): Que trần; C ~ ε_lỏng × A / d.\nHạn chế: Bám cặn thay đổi ε → sai số. Cần bù nhiệt độ.',
        equip:'Endress+Hauser Solicap\nVega VEGACAP\nRosemount 5300 (guided radar)',
        params:'C = ε×A/d\nΔC = 5-20 pF/meter level\nAnh hưởng: nhiệt độ, ε_r thay đổi' },

      { id:10, stt:'L5', cat:'level', name:'Ultrasonic & Radar Level – Đo mức không tiếp xúc', sub:'US: d=(SoS×t)/2 · Radar FMCW Δf→d · Không tiếp xúc · Chính xác cao',
        cells:[
          { l:'Ultrasonic',     c:[{t:'d=(SoS×t)/2',k:'ultrasonic_l'},{t:'15-200 kHz',k:'ultrasonic_l'},{t:'Không tiếp xúc',k:'ultrasonic_l'}] },
          { l:'Radar FMCW',     c:[{t:'Δf → time → distance',k:'radar_fmcw'},{t:'6 GHz hoặc 26 GHz',k:'radar_fmcw'},{t:'Kháng hơi/bụi',k:'radar_fmcw'}] },
          { l:'Ưu Radar hơn US',v:'Không ảnh hưởng nhiệt độ, hơi nước, hơi hóa chất' },
          { l:'Hãng tại NM',    c:[{t:'E+H FMU/FMR',k:'radar_fmcw'},{t:'Rosemount 5400/5600',k:'radar_fmcw'}] },
        ],
        goal:'Đo mức không tiếp xúc bằng sóng âm (Ultrasonic) hoặc sóng vi ba (Radar FMCW). Radar ưu việt hơn trong môi trường hơi nước, nhiệt độ cao.',
        detail:'Ultrasonic Level:\n• Phát xung siêu âm → phản xạ từ bề mặt lỏng → đo thời gian\n• d = (SoS × t) / 2; SoS ≈ 343 m/s (thay đổi theo nhiệt độ)\n• Deadband: vùng mù ~0.3m gần sensor\n• Nhược: bị ảnh hưởng bởi nhiệt độ, hơi, bụi\nRadar FMCW:\n• Phát sóng vi ba liên tục, tần số quét tuyến tính\n• Sóng phản xạ → Δf giữa phát và thu → tỷ lệ với khoảng cách\n• d = (Δf × c) / (2 × BW/T)\n• 6 GHz (ăng-ten lớn, kháng foam/bọt), 26 GHz (ăng-ten nhỏ, chính xác ±1mm)\n• Không bị ảnh hưởng bởi hơi, nhiệt độ, bụi → dùng cho bình áp lực',
        equip:'E+H FMU95 (Ultrasonic)\nE+H FMR50/60 (FMCW Radar)\nRosemount 5400/5600 (Radar)',
        params:'US: d=(SoS×t)/2, ±2mm\nRadar: d via Δf, ±1mm\nRadar: kháng hơi, hóa chất, bụi' },

      /* ─── LƯU LƯỢNG ─── */
      { id:11, stt:'F1', cat:'flow', name:'DP Flowmeter – Orifice Plate (Tấm lỗ)', sub:'Q=Av · Bernoulli · Q∝√ΔP · Cd≈0.6 · Phổ biến nhất NM',
        cells:[
          { l:'Phương trình',    c:[{t:'Q=A×v (liên tục)',k:'orifice'},{t:'Bernoulli ΔP∝v²',k:'orifice'}] },
          { l:'Công thức',       v:'Q = Cd × A₂ × √(2ΔP/ρ); Q ∝ √ΔP (square-root)' },
          { l:'Kiểu Orifice',    c:[{t:'Concentric (phổ biến)'},{t:'Eccentric (bùn/2 pha)'},{t:'Segmental (hạt nhỏ)'}] },
          { l:'Tap kiểu',        v:'Corner, Flange, D-D/2, Vena contracta' },
          { l:'Nhược điểm',      v:'Tổn thất áp lớn (~50% ΔP), bị cặn bám, độ chính xác ±0.5-1%' },
        ],
        goal:'Phương pháp đo lưu lượng phổ biến nhất tại NM Đạm Cà Mau. Đơn giản, rẻ, có thể thay thế tại chỗ. Dùng với DP Transmitter Rosemount 3051.',
        detail:'Nguyên lý Bernoulli + Liên tục:\nQ = A₁v₁ = A₂v₂ → v₂ = v₁ × (D₁/D₂)² → P₁ − P₂ = ½ρ(v₂² − v₁²)\nQ = Cd × A₂ × √(2ΔP/ρ)\nCd: hệ số xả = 0.60-0.65 (orifice tấm phẳng)\nβ = d/D (tỷ số đường kính): thường 0.3-0.75\nSquare-root: Q ∝ √ΔP → cần khai căn trong DCS/transmitter\nFlow compensation: Q bù T và P cho khí/hơi',
        equip:'Orifice plate (Carbon/SS)\nRosemount 3051C DP TX\nOrifice flange + tapping',
        params:'Q = Cd×A₂×√(2ΔP/ρ)\nβ = 0.3-0.75 (tiêu chuẩn ISO 5167)\nĐộ chính xác: ±0.5-1% FS\nQ ∝ √ΔP (square-root)' },

      { id:12, stt:'F2', cat:'flow', name:'DP Flowmeter – Venturi & Annubar', sub:'Venturi: ΔP thấp · Annubar: pitot trung bình · ISO 5167',
        cells:[
          { l:'Venturi',    c:[{t:'Phục hồi áp tốt (~90%)',k:'orifice'},{t:'Chính xác cao ±0.3%',k:'orifice'}] },
          { l:'Annubar',    c:[{t:'Averaging Pitot Tube',k:'orifice'},{t:'Ít tổn thất áp',k:'orifice'},{t:'Ống lớn D>200mm',k:'orifice'}] },
          { l:'So với Orifice', v:'Venturi/Annubar: tổn thất áp thấp hơn nhiều' },
          { l:'Nguyên lý', v:'Cùng nguyên lý Q∝√ΔP như Orifice' },
        ],
        goal:'Venturi: độ chính xác cao, tổn thất áp thấp, ống lớn có hàm lượng cặn. Annubar (Averaging Pitot): tổn thất áp gần bằng 0, phù hợp đường kính lớn.',
        detail:'Venturi Meter:\n• Thu dần – họng – mở rộng từ từ → phục hồi áp ~90%\n• Q = Cd × A_throat × √(2ΔP/ρ), Cd ≈ 0.98 (tốt hơn orifice)\n• Dùng khi: lưu chất có cặn, hơi, khí ướt (không tắc)\nAnnubar (e.g. Rosemount 485 Annubar):\n• Thanh pitot nhiều lỗ đo áp trung bình cắt ngang ống\n• ΔP = P_total − P_static → Q tính theo Bernoulli\n• Tổn thất áp < 5% → tiết kiệm năng lượng lớn\n• Phù hợp ống đường kính lớn (D > 200mm), không cần flanges',
        equip:'Rosemount 485 Annubar\nVenturi tube SS/CS\nDP TX Rosemount 3051',
        params:'Venturi: Cd≈0.98, ΔP recovery 90%\nAnnubar: ΔP loss <5%\nCả 2: Q ∝ √ΔP' },

      { id:13, stt:'F3', cat:'flow', name:'Vortex Flowmeter – Dòng xoáy Karman', sub:'Bluff body · Strouhal S≈0.17 · f∝v · Hơi & Khí & Lỏng sạch',
        cells:[
          { l:'Nguyên lý',      c:[{t:'f = S×v/d, S≈0.17',k:'vortex_s'},{t:'Karman vortex street',k:'vortex_s'}] },
          { l:'Đầu đo tần số',  c:[{t:'Piezoelectric sensor'},{t:'Capacitive sensor'}] },
          { l:'Yêu cầu',        v:'Re > 10000 – Không dùng cho lưu chất nhớt cao' },
          { l:'Ưu điểm',        v:'Không bộ phận chuyển động, tổn thất áp thấp, ổn định dài hạn' },
          { l:'Ứng dụng NM',    v:'Hơi nước, N₂, Air, chất lỏng sạch' },
        ],
        goal:'Đo lưu lượng bằng tần số xoáy Karman. Không có bộ phận chuyển động. Xuất sắc cho hơi nước, khí, lỏng sạch tại NM. Yokogawa digitalYEWFLO.',
        detail:'Nguyên lý Karman Vortex Street:\nKhi Re > 10000, dòng chảy qua bluff body sinh xoáy Karman xen kẽ 2 bên.\nTần số xoáy: f = S × v / d\n• S ≈ 0.17 (Strouhal number, hằng số của thiết bị)\n• v: vận tốc dòng (m/s)\n• d: chiều rộng bluff body (m)\nQ = f × d/S × A_pipe\nƯu điểm: Không có bộ phận chuyển động → độ tin cậy cao, bảo trì thấp.\nHạn chế: Không dùng cho lưu chất nhớt (μ cao), lưu lượng thấp (<0.15 m/s), hoặc khi có 2 pha.',
        equip:'Yokogawa digitalYEWFLO\nRosemount 8800D\nEndress+Hauser Prowirl',
        params:'f = S×v/d, S≈0.17\nRe > 10000 (yêu cầu)\nDải: 0.15–10 m/s\nĐộ chính xác: ±0.5-1%' },

      { id:14, stt:'F4', cat:'flow', name:'Magnetic Flowmeter – Điện từ Faraday', sub:'E=BLv · Chỉ lỏng dẫn điện · Không ΔP · Không bộ phận chuyển động',
        cells:[
          { l:'Định luật Faraday', c:[{t:'E = B×L×v',k:'magflow'},{t:'B: từ trường (Tesla)',k:'magflow'}] },
          { l:'Yêu cầu',          c:[{t:'Lỏng dẫn điện ≥5 μS/cm',k:'magflow'},{t:'KHÔNG dùng cho khí',k:'magflow'}] },
          { l:'Ưu điểm',          c:[{t:'Tổn thất áp = 0',k:'magflow'},{t:'Không bộ phận động',k:'magflow'}] },
          { l:'Hãng tại NM',      c:[{t:'Yokogawa ADMAG',k:'magflow'},{t:'E+H Promag',k:'magflow'}] },
        ],
        goal:'Đo lưu lượng chất lỏng dẫn điện (nước, dung dịch muối, axit, kiềm) không có tổn thất áp. Không có bộ phận chuyển động, bảo trì rất thấp.',
        detail:'Định luật Faraday: Khi dây dẫn (lỏng dẫn điện) di chuyển vuông góc từ trường:\nE = B × L × v\n• E: EMF cảm ứng đo tại 2 điện cực (μV)\n• B: từ trường tạo bởi cuộn dây (Tesla)\n• L: khoảng cách 2 điện cực (m, = đường kính ống)\n• v: vận tốc trung bình (m/s)\nQ = E × D / (B × k)\nYêu cầu bắt buộc: Lỏng DẪN ĐIỆN ≥ 5 μS/cm.\nKhông dùng cho: nước cất, dầu, khí, hơi nước.\nLót: PTFE, polyurethane, ebonite (chống ăn mòn).',
        equip:'Yokogawa ADMAG AXW\nE+H Promag 10/50/53\nRosemount 8705/8707',
        params:'E = B×L×v\nDẫn điện: ≥ 5 μS/cm\nĐộ chính xác: ±0.2-0.5%\nΔP = 0 (không tổn thất áp)' },

      { id:15, stt:'F5', cat:'flow', name:'Coriolis Mass Flowmeter – Đo khối lượng trực tiếp', sub:'ΔT shift = Mass flow · Density = 1/f² · Multi-variable · Micro Motion',
        cells:[
          { l:'Nguyên lý',       c:[{t:'Mass ∝ ΔT (lệch pha)',k:'coriolis'},{t:'Density ∝ 1/f²',k:'coriolis'}] },
          { l:'Đầu ra',          c:[{t:'Mass flow (kg/h)',k:'coriolis'},{t:'Density (kg/m³)',k:'coriolis'},{t:'Temperature (°C)',k:'coriolis'}] },
          { l:'Ưu điểm',         v:'Đo trực tiếp mass, không cần bù T và P' },
          { l:'Hãng tại NM',     c:[{t:'Emerson Micro Motion',k:'coriolis'},{t:'E+H Promass',k:'coriolis'}] },
        ],
        goal:'Đo khối lượng dòng chảy trực tiếp không phụ thuộc nhiệt độ, áp suất, hoặc thành phần. Đồng thời đo density và nhiệt độ. Chính xác ±0.1% mass.',
        detail:'Nguyên lý: Ống đo hình chữ U (hoặc thẳng) rung ở tần số cộng hưởng.\nKhi có dòng chảy → lực Coriolis tác dụng vuông góc với ống rung → ống xoắn.\nĐộ xoắn (lệch pha ΔT giữa 2 điểm đo) ∝ Mass Flow Rate.\nTần số rung ∝ 1/√mật_độ → Density = k/f²\nMulti-variable: 1 thiết bị đo Mass Flow + Density + Temperature.\nChính xác: ±0.1% mass flow, ±0.5 kg/m³ density.\nHạn chế: Giá cao, tổn thất áp vừa, nhạy cảm với rung bên ngoài, khó dùng cho khí áp thấp.',
        equip:'Micro Motion ELITE (Emerson)\nE+H Promass 83/84/85\nYokogawa Rotamass',
        params:'Mass flow: ±0.1%\nDensity: ±0.5 kg/m³\nTemp: ±1°C\nMulti-var: Mass+Density+T' },

      /* ─── PHÂN TÍCH ─── */
      { id:16, stt:'A1', cat:'ana', name:'Mass Spectrometer – Phân tích khí đa thành phần', sub:'10-point online · CH4/CO/CO2/H2/N2/NH3 · NM Đạm Cà Mau',
        cells:[
          { l:'Nguyên lý',       v:'Ion hóa phân tử → tách theo m/z → đo dòng ion' },
          { l:'Cấu tử phân tích',c:[{t:'CH4, CO, CO2',k:'ms_gc'},{t:'H2, N2, NH3',k:'ms_gc'},{t:'Purge gas',k:'ms_gc'}] },
          { l:'Số điểm lấy mẫu',v:'10-point online sampling tại NM Đạm Cà Mau' },
          { l:'Ưu điểm',         v:'Phân tích đồng thời nhiều cấu tử, tốc độ nhanh' },
        ],
        goal:'Hệ thống phân tích khí quá trình 10 điểm lấy mẫu online liên tục. Phân tích đồng thời CH4, CO, CO2, H2, N2, NH3 tại các điểm chủ yếu trong dây chuyền Ammonia.',
        detail:'Nguyên lý Mass Spectrometer:\n• Ion hóa phân tử khí bằng chùm electron\n• Tách ion theo tỷ số m/z (mass/charge) trong từ trường\n• Detector đo dòng ion → tính nồng độ từng cấu tử\n10 điểm lấy mẫu tại NM:\n• 04AE_2041: Process gas outlet F04201\n• 04AE_2051: Process gas inlet E04209\n• 04AE_2076: Process gas outlet R04205\n• 04AE_5001: Synthesis gas inlet E04503\n• 04AE_5002: Synthesis gas outlet E04503\n• 04AE_5003: Purge gas Sample Stream\n• 04AE_2077: Synthesis gas outlet R04204\n• 04AE_3032: Synthesis gas outlet S04311\n• 04AE_2001: Natural gas\n• 04AE_5541: Exhaust gas outlet C04551',
        equip:'Mass Spectrometer System\n10-point sample selector valve\nKiểm tra CH4/CO/CO2/H2/N2/NH3',
        params:'Cấu tử: CH4, CO, CO2, H2, N2, NH3\n10 điểm online sampling\nChu kỳ: ~1 phút/điểm' },

      { id:17, stt:'A2', cat:'ana', name:'Gas Chromatograph – Sắc ký khí', sub:'GC1000 Yokogawa · H2/O2/CO2/CH4/NH3 · Flare & Urea section',
        cells:[
          { l:'Model tại NM',   c:[{t:'Yokogawa GC1000 Mark II',k:'ms_gc'}] },
          { l:'Cấu tử',         c:[{t:'H2 0-50%',k:'ms_gc'},{t:'O2 0-20%',k:'ms_gc'},{t:'CO2 0-1%',k:'ms_gc'},{t:'CH4 0-10%',k:'ms_gc'},{t:'NH3 0-5%',k:'ms_gc'}] },
          { l:'Vị trí lắp',     v:'Flare section + Urea section' },
          { l:'Nguyên lý',      v:'Tách cấu tử theo thời gian lưu giữ trong cột GC (carrier gas He/N2)' },
        ],
        goal:'Gas Chromatograph GC1000 Mark II (Yokogawa) phân tích thành phần khí tại Flare và Urea section. Chu kỳ phân tích 2-10 phút cho 5 cấu tử.',
        detail:'Nguyên lý GC:\n• Mẫu khí nạp vào → carrier gas (He/N2) mang qua cột phân tách\n• Mỗi cấu tử có ái lực khác nhau với pha tĩnh trong cột → thoát ra ở thời gian khác nhau (retention time)\n• Detector (TCD/FID) đo tín hiệu → định tính và định lượng\nGC1000 Mark II (Yokogawa) tại NM:\n• H2: 0-50 vol%\n• O2: 0-20 vol%\n• CO2: 0-1 vol%\n• CH4: 0-10 vol%\n• NH3: 0-5 vol%\nVị trí: Flare section (giám sát xả), Urea section',
        equip:'Yokogawa GC1000 Mark II\nCarrier gas: He/N2\nDetector: TCD (Thermal Conductivity)',
        params:'H2: 0-50% | O2: 0-20%\nCO2: 0-1% | CH4: 0-10%\nNH3: 0-5%\nChu kỳ: 2-10 phút/lần' },

      { id:18, stt:'A3', cat:'ana', name:'CEMS & O2/CO/CO2 Analyzers – Giám sát phát thải', sub:'NOx/CO/O2 · Rosemount X-Stream · EMS môi trường · O2 Analyzer',
        cells:[
          { l:'CEMS tại NM',    c:[{t:'X-Stream XEFD (Emerson)',k:'cems_ana'},{t:'01 Boiler + 01 Reforming',k:'cems_ana'}] },
          { l:'Chỉ tiêu CEMS',  c:[{t:'NOx',k:'cems_ana'},{t:'CO',k:'cems_ana'},{t:'O2',k:'cems_ana'}] },
          { l:'O2 Analyzer',    v:'Giám sát O2 tại Boiler, Reforming, N2 plant, CO2 compressor' },
          { l:'EMS',            v:'NOx, CO, NH3, áp suất, tiếng ồn, bụi, gió, mưa, nhiệt độ' },
        ],
        goal:'CEMS giám sát liên tục NOx/CO/O2 trong khí xả tại Boiler và Reforming. O2 Analyzer giám sát hiệu suất đốt cháy. EMS theo dõi chỉ tiêu môi trường toàn nhà máy.',
        detail:'CEMS (Continuous Emissions Monitoring System):\n• Model: Rosemount X-Stream XEFD (Emerson)\n• 02 hệ: 01 tại Boiler + 01 tại Reforming\n• Đo NOx: Chemiluminescence hoặc NDIR UV\n• Đo CO: NDIR (Non-Dispersive Infrared)\n• Đo O2: Paramagnetic cell\n• Kết quả: báo cáo cơ quan môi trường định kỳ\nO2 Analyzers:\n• Giám sát nồng độ O2 tại Boiler (hiệu suất đốt), Reforming, N2 production\n• Nguyên lý: Paramagnetic hoặc Zirconia cell\nEMS: Giám sát thêm: NH3, áp suất khí quyển, tiếng ồn, độ ẩm, tốc độ gió, bụi PM, lượng mưa, nhiệt độ môi trường.',
        equip:'Rosemount X-Stream XEFD (CEMS)\nO2 Analyzer tại 4 khu vực\nEMS station toàn nhà máy',
        params:'CEMS: NOx, CO, O2\nO2: tại Boiler/Reforming/N2/CO2 comp\nEMS: 10 thông số môi trường' },

      { id:19, stt:'A4', cat:'ana', name:'pH & Conductivity Analyzers – Chất lượng nước', sub:'pH: 15 máy Yokogawa · Conductivity: 24 máy · DEMI/Cooling/Boiler',
        cells:[
          { l:'pH Analyzer',     c:[{t:'15 máy Yokogawa',k:'ph_cond'},{t:'Glass electrode',k:'ph_cond'}] },
          { l:'Áp dụng pH',      c:[{t:'DEMI water'},{t:'Cooling water'},{t:'Boiler water'},{t:'Fresh water'}] },
          { l:'Conductivity',    c:[{t:'24 máy Yokogawa',k:'ph_cond'},{t:'μS/cm hoặc mS/cm',k:'ph_cond'}] },
          { l:'Tầm quan trọng',  v:'Kiểm soát ăn mòn, scale trong lò hơi và tháp làm mát' },
        ],
        goal:'Giám sát chất lượng nước trong hệ thống DEMI, Cooling water, Boiler water. pH kiểm soát ăn mòn, Conductivity đánh giá tổng lượng ion. Yokogawa tại NM.',
        detail:'pH Analyzer:\n• Nguyên lý: Điện cực thủy tinh tạo EMF tỷ lệ với log[H⁺]: E = 59.16×(7-pH) mV (25°C)\n• Chuẩn 2 điểm: pH 4.01 + pH 7.00 hoặc pH 7.00 + pH 10.01\n• 15 máy Yokogawa: DEMI water, Cooling water tower, Boiler water, Fresh water\nConductivity Analyzer:\n• Đo khả năng dẫn điện = tổng lượng ion hòa tan\n• Đơn vị: μS/cm (nước cất) đến mS/cm (nước biển)\n• 24 máy Yokogawa tại NM\n• DEMI water: < 0.1 μS/cm (tinh khiết)\n• Cooling water: giám sát thay đổi muối\n• Boiler water: ≤ 10 μS/cm (ngăn scale)',
        equip:'Yokogawa PH202 (pH)\nYokogawa SC202 (conductivity)\nHãng: Yokogawa (NM: 15 pH + 24 Cond)',
        params:'pH: 0-14, ±0.01 pH\nConductivity: 0.01 μS - 500 mS/cm\n15 pH + 24 Cond tại NM' },

      { id:20, stt:'A5', cat:'ana', name:'Gas Detectors – Đầu dò khí F&G', sub:'NH3/CO/Cháy nổ · 108 đầu Honeywell XCD · F&G System · ESD',
        cells:[
          { l:'Số lượng tại NM',  c:[{t:'108 đầu dò Honeywell XCD',k:'gasdet'}] },
          { l:'Loại khí',         c:[{t:'NH3 – 88 đầu (Electrochemical)',k:'gasdet'},{t:'CO – 4 đầu',k:'gasdet'},{t:'Flammable – 15 đầu (Catalytic)',k:'gasdet'}] },
          { l:'Nguyên lý đo',     c:[{t:'Catalytic bead (khí cháy)',k:'gasdet'},{t:'Electrochemical (NH3/CO)',k:'gasdet'},{t:'NDIR (CH4/CO)',k:'gasdet'}] },
          { l:'Tích hợp',         c:[{t:'F&G System → ESD interlock',k:'gasdet'}] },
        ],
        goal:'108 đầu dò khí Honeywell XCD phát hiện sớm khí độc (NH3, CO) và khí cháy nổ tại NM. Kết nối vào hệ thống F&G/ESD để kích hoạt alarm và interlock an toàn.',
        detail:'Gas Detectors tại NM Đạm Cà Mau:\n• Tổng: 108 đầu Honeywell XCD Series\n• NH3 (Ammonia): 88 đầu – Electrochemical cell – ngưỡng alarm 25/50 ppm\n• CO (Carbon Monoxide): 4 đầu – Electrochemical – ngưỡng 25/50 ppm (TWA/STEL)\n• Flammable gas: 15 đầu – Catalytic bead – ngưỡng 10/25% LEL\nNguyên lý:\n• Catalytic bead (Pellistor): khí cháy → oxy hóa trên hạt xúc tác → nhiệt → điện trở thay đổi\n• Electrochemical: khí + điện cực → phản ứng điện hóa → dòng điện ∝ nồng độ\n• NDIR: hấp thụ tia hồng ngoại đặc trưng của từng khí\nKết nối vào FGS (TRICONEX SIL-3) → ESD → alarm/shutdown',
        equip:'Honeywell XCD Series (NM: 108 units)\nElectrochemical: NH3/CO/H2S\nCatalytic bead: Flammable\nNIR: CH4, CO2',
        params:'88 NH3 + 4 CO + 15 Flammable = 108\nNgưỡng NH3: 25 ppm (alarm)/50 ppm\nFlammable: 10% LEL/25% LEL' },
    ],

    mindmap: {
      nodes: [
        { id:'root',      x:530, y:293, w:250, h:72, label:'THIẾT BỊ ĐO LƯỜNG\nField Instrumentation' },
        { id:'temp_cat',  x:265, y:55,  w:175, h:46, label:'NHIỆT ĐỘ\n(Temperature)',  cat:'temp',  sub:'input' },
        { id:'pres_cat',  x:265, y:265, w:175, h:46, label:'ÁP SUẤT\n(Pressure)',      cat:'pres',  sub:'input' },
        { id:'level_cat', x:265, y:480, w:175, h:46, label:'MỨC\n(Level)',             cat:'level', sub:'input' },
        { id:'flow_cat',  x:955, y:100, w:200, h:46, label:'LƯU LƯỢNG\n(Flow)',         cat:'flow',  sub:'input' },
        { id:'ana_cat',   x:955, y:490, w:200, h:46, label:'PHÂN TÍCH\n(Analytical)',   cat:'ana',   sub:'input' },
        { id:'rtd',    x:20, y:18,  w:190, h:36, label:'RTD PT100\nR=R₀[1+α(T−T₀)], α=0.00392', cat:'temp', sub:'product' },
        { id:'tc',     x:20, y:60,  w:190, h:36, label:'Thermocouple\nSeebeck V=(T−Tref)×S',     cat:'temp' },
        { id:'temptx', x:20, y:102, w:190, h:36, label:'Temp TX + Thermowell\n4-20mA·HART·Rosemount 644', cat:'temp' },
        { id:'pgauge', x:20, y:228, w:190, h:36, label:'Pressure Gauge\nBourdon tube · Đọc tại chỗ',  cat:'pres' },
        { id:'ptx',    x:20, y:270, w:190, h:36, label:'Pressure TX\n3051C · Differential Capacitance', cat:'pres', sub:'product' },
        { id:'dptx',   x:20, y:312, w:190, h:36, label:'DP TX + Manifold\nΔP=P₁−P₂ · 3-valve/5-valve', cat:'pres' },
        { id:'lgauge', x:20, y:450, w:190, h:36, label:'Level Gauge\nSight glass · Magnetic (MLG)',     cat:'level' },
        { id:'dplvl',  x:20, y:494, w:190, h:36, label:'DP Level\nΔP=ρ×g×h · Wet/Dry leg',            cat:'level', sub:'product' },
        { id:'buoy_n', x:20, y:538, w:190, h:36, label:'Buoyancy Level\nFb=ρ×g×A×h · Float/Displacer', cat:'level' },
        { id:'cap_n',  x:20, y:582, w:190, h:36, label:'Capacitance Level\nC=ε×A/d · Dẫn/Không dẫn',   cat:'level' },
        { id:'usradar',x:20, y:626, w:190, h:36, label:'Ultrasonic+Radar\nd=(SoS×t)/2 · FMCW Δf',      cat:'level' },
        { id:'orif_n', x:1215, y:50,  w:165, h:36, label:'Orifice Plate\nQ=Cd×A₂×√(2ΔP/ρ) · ISO5167', cat:'flow', sub:'product' },
        { id:'venturi',x:1215, y:94,  w:165, h:36, label:'Venturi/Annubar\nCd≈0.98 · ΔP thấp',          cat:'flow' },
        { id:'vortex', x:1215, y:138, w:165, h:36, label:'Vortex\nf=S×v/d, S≈0.17',                      cat:'flow' },
        { id:'magf_n', x:1215, y:182, w:165, h:36, label:'Magnetic (EMF)\nE=B×L×v · Lỏng dẫn ≥5μS/cm', cat:'flow' },
        { id:'coril_n',x:1215, y:226, w:165, h:36, label:'Coriolis\nMass∝ΔT · Density∝1/f²',             cat:'flow' },
        { id:'ms_n',   x:1215, y:445, w:165, h:36, label:'Mass Spectrometer\n10-point · CH4/CO/H2/N2',    cat:'ana',  sub:'product' },
        { id:'gc_n',   x:1215, y:489, w:165, h:36, label:'Gas Chromatograph\nGC1000 Yokogawa',             cat:'ana' },
        { id:'cems_n', x:1215, y:533, w:165, h:36, label:'CEMS\nNOx/CO/O2 · X-Stream XEFD',               cat:'ana' },
        { id:'ph_n',   x:1215, y:577, w:165, h:36, label:'pH & Conductivity\n15 pH + 24 Cond · Yokogawa', cat:'ana' },
        { id:'gasdet_n',x:1215,y:621, w:165, h:36, label:'Gas Detectors\n108 Honeywell XCD · F&G',        cat:'ana' },
      ],
      edges: [
        { from:'root', to:'temp_cat',  color:'orange' },
        { from:'root', to:'pres_cat',  color:'cyan'   },
        { from:'root', to:'level_cat', color:'green'  },
        { from:'root', to:'flow_cat',  color:'purple' },
        { from:'root', to:'ana_cat',   color:'amber'  },
        { from:'temp_cat',  to:'rtd',     color:'orange' },
        { from:'temp_cat',  to:'tc',      color:'orange' },
        { from:'temp_cat',  to:'temptx',  color:'orange' },
        { from:'pres_cat',  to:'pgauge',  color:'cyan' },
        { from:'pres_cat',  to:'ptx',     color:'cyan' },
        { from:'pres_cat',  to:'dptx',    color:'cyan' },
        { from:'level_cat', to:'lgauge',  color:'green' },
        { from:'level_cat', to:'dplvl',   color:'green' },
        { from:'level_cat', to:'buoy_n',  color:'green' },
        { from:'level_cat', to:'cap_n',   color:'green' },
        { from:'level_cat', to:'usradar', color:'green' },
        { from:'flow_cat',  to:'orif_n',  color:'purple' },
        { from:'flow_cat',  to:'venturi', color:'purple' },
        { from:'flow_cat',  to:'vortex',  color:'purple' },
        { from:'flow_cat',  to:'magf_n',  color:'purple' },
        { from:'flow_cat',  to:'coril_n', color:'purple' },
        { from:'ana_cat',   to:'ms_n',    color:'amber' },
        { from:'ana_cat',   to:'gc_n',    color:'amber' },
        { from:'ana_cat',   to:'cems_n',  color:'amber' },
        { from:'ana_cat',   to:'ph_n',    color:'amber' },
        { from:'ana_cat',   to:'gasdet_n',color:'amber' },
        { from:'dptx',      to:'dplvl',   color:'cyan', dashed:true, label:'DP→Level' },
        { from:'dptx',      to:'orif_n',  color:'cyan', dashed:true, label:'DP→Flow'  },
      ],
      zones: [
        { x:0,   y:0,   w:455, h:175, label:'NHIỆT ĐỘ',    color:'esd'     },
        { x:0,   y:180, w:455, h:195, label:'ÁP SUẤT',     color:'amo'     },
        { x:0,   y:380, w:455, h:320, label:'MỨC',         color:'urea'    },
        { x:935, y:0,   w:465, h:385, label:'LƯU LƯỢNG',   color:'aux'     },
        { x:935, y:390, w:465, h:310, label:'PHÂN TÍCH',   color:'granule' },
        { x:480, y:250, w:440, h:195, label:'',             color:'mid'     },
      ],
      legend: [
        { label:'Nhiệt độ',  color:'#dc2626' },
        { label:'Áp suất',   color:'#0891b2' },
        { label:'Mức',       color:'#047857' },
        { label:'Lưu lượng', color:'#7c3aed' },
        { label:'Phân tích', color:'#d97706' },
      ]
    },

    flashcards: [
      { q:'RTD PT100: điện trở tại 0°C là bao nhiêu? Công thức tính R?', a:'R₀ = 100 Ω tại 0°C. RT = R₀[1 + α(T−T₀)] với α = 0.00392 Ω/Ω·°C (tiêu chuẩn IEC 60751).', cat:'temp' },
      { q:'Tại sao dùng 3-wire hoặc 4-wire cho RTD thay vì 2-wire?', a:'2-wire: điện trở dây dẫn cộng vào → sai số. 3-wire bù 1 dây, 4-wire bù cả 2 dây → loại bỏ sai số đường dây. 4-wire chính xác nhất.', cat:'temp' },
      { q:'Thermocouple type K có hệ số Seebeck là bao nhiêu? Dải đo?', a:'S ≈ 41 μV/°C (Chromel-Alumel). Dải đo: −200 đến +1260°C. Phổ biến nhất trong công nghiệp.', cat:'temp' },
      { q:'CJC là gì? Tại sao cần CJC cho thermocouple?', a:'CJC = Cold Junction Compensation. Thermocouple đo hiệu nhiệt độ, không phải tuyệt đối. Transmitter đo nhiệt độ đầu nối lạnh (môi trường) và bù tự động để tính T_process chính xác.', cat:'temp' },
      { q:'Thermowell dùng để làm gì? Rủi ro nào cần kiểm tra?', a:'Thermowell bảo vệ cảm biến khỏi áp suất và ăn mòn. Rủi ro: rung cộng hưởng Strouhal → gãy thermowell. Phải kiểm tra Wake Frequency Calculation (ASME PTC 19.3).', cat:'temp' },
      { q:'DP Transmitter: phân biệt Gauge, Absolute, Differential?', a:'Gauge (Pg): đo so với khí quyển (P_abs − P_atm). Absolute: đo so với chân không hoàn toàn. Differential (ΔP): đo hiệu P₁ − P₂ (dùng cho lưu lượng, mức, lọc).', cat:'pres' },
      { q:'Quy trình zero DP Transmitter tại chỗ (manifold 3-valve)?', a:'1. Mở equalizer (cân bằng áp 2 bên). 2. Đóng 2 valve isolation (cách ly process). 3. Điều chỉnh zero TX = 0%. 4. Đóng equalizer. 5. Mở 2 valve isolation. 6. Kiểm tra output.', cat:'pres' },
      { q:'Manifold 3-valve gồm những van nào? Dùng khi nào?', a:'3-valve = 2 Isolation (cô lập process) + 1 Equalization (cân bằng áp 2 bên). Dùng cho DP Transmitter. 5-valve thêm 2 Blowdown (xả cặn) cho vị trí quan trọng.', cat:'pres' },
      { q:'Phương trình tính mức bằng DP hydrostatic là gì?', a:'ΔP = ρ × g × h → h = ΔP / (ρ × g). ρ: mật độ chất lỏng (kg/m³), g: gia tốc trọng trường (9.81 m/s²). Với bình kín: cần bù offset từ leg đầy chất lỏng.', cat:'level' },
      { q:'Sự khác nhau giữa Float và Displacer trong đo mức?', a:'Float: nổi hoàn toàn trên mặt lỏng, di chuyển theo mức. Displacer: luôn chìm hoàn toàn, đo biến thiên lực nổi Fb=ρgAh khi mức thay đổi. Displacer dùng cho bình áp lực và đo giao diện 2 pha.', cat:'level' },
      { q:'Radar FMCW khác gì với Ultrasonic trong đo mức?', a:'Ultrasonic dùng sóng âm, bị ảnh hưởng bởi nhiệt độ, hơi, bụi. Radar dùng sóng vi ba, không bị ảnh hưởng bởi hơi nước, nhiệt độ, bụi → dùng được cho bình áp lực kín.', cat:'level' },
      { q:'Phương trình Orifice flowmeter: Q = ? Tại sao gọi là square-root?', a:'Q = Cd × A₂ × √(2ΔP/ρ). Q tỷ lệ với √ΔP → gọi là "square-root characterization". DCS phải khai căn bậc 2 tín hiệu DP để có Q tuyến tính.', cat:'flow' },
      { q:'Vortex flowmeter: Strouhal number là gì? Tần số xoáy tính thế nào?', a:'S ≈ 0.17 = hằng số tỷ lệ giữa bước sóng xoáy và chiều rộng bluff body. f = S × v / d. Q = f × d/S × A. Tần số xoáy tỷ lệ tuyến tính với vận tốc dòng.', cat:'flow' },
      { q:'Magnetic flowmeter yêu cầu gì đối với chất lỏng? Tại sao không dùng cho khí?', a:'Chất lỏng phải DẪN ĐIỆN ≥ 5 μS/cm. Khí không dẫn điện → không tạo EMF theo định luật Faraday E=B×L×v → không đo được. Nước cất cũng không đủ dẫn điện.', cat:'flow' },
      { q:'Coriolis flowmeter đo được những thông số nào? Nguyên lý là gì?', a:'Multi-variable: Mass Flow + Density + Temperature. Nguyên lý: ống rung → lực Coriolis → lệch pha ΔT giữa 2 điểm đo ∝ Mass. Tần số rung ∝ 1/√ρ → Density = k/f².', cat:'flow' },
      { q:'Mass Spectrometer tại NM Đạm Cà Mau có bao nhiêu điểm lấy mẫu? Phân tích gì?', a:'10 điểm online sampling. Phân tích đồng thời: CH4, CO, CO2, H2, N2, NH3. Tại các điểm chủ yếu trong dây chuyền Ammonia từ Natural gas đến Synthesis gas.', cat:'ana' },
      { q:'CEMS tại NM đo những gì? Model thiết bị là gì?', a:'CEMS đo liên tục: NOx, CO, O2. Model: Rosemount X-Stream XEFD (Emerson). Lắp tại 01 Boiler + 01 Reforming. Kết quả báo cáo cho cơ quan môi trường.', cat:'ana' },
      { q:'Gas Detector tại NM: có bao nhiêu đầu? Loại nào và nguyên lý gì?', a:'108 đầu Honeywell XCD Series: 88 NH3 (Electrochemical), 4 CO (Electrochemical), 15 Flammable (Catalytic bead). Catalytic: oxi hóa khí → nhiệt → ΔR. Electrochemical: phản ứng → dòng điện.', cat:'ana' },
      { q:'pH Analyzer: điện cực đo pH là loại gì? Cần chuẩn mấy điểm?', a:'Điện cực thủy tinh (glass electrode). Cần chuẩn 2 điểm: pH 4.01 + pH 7.00 (hoặc 7.00 + 10.01). 15 máy Yokogawa tại NM đo DEMI, Cooling water, Boiler water.', cat:'ana' },
    ]
  }"""

src = open('C:/Users/PHUOC VINH/PVCFC-KNL/other-skills.js', 'r', encoding='utf-8').read()
if 'instru:' in src:
    print('instru already present, skipping.')
else:
    patched = src.rstrip()
    if patched.endswith('};'):
        patched = patched[:-2].rstrip() + INSTRU_SKILL + '\n};'
    else:
        raise ValueError('Could not find closing }; in other-skills.js')
    with open('C:/Users/PHUOC VINH/PVCFC-KNL/other-skills.js', 'w', encoding='utf-8') as f:
        f.write(patched)
    print('OK: instru skill appended to other-skills.js')
