import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

content = open('C:/Users/PHUOC VINH/PVCFC-KNL/other-skills.js', 'r', encoding='utf-8').read()
start = content.index('  van: {')
end   = content.index('  dien: {')
prefix = content[:start]
suffix = content[end:]

NEW_VAN = r"""  van: {
    id: 'van',
    name: 'Thiết bị chấp hành – Van điều khiển',
    icon: '🔧',
    color: '#7c3aed',
    renderMode: 'van',
    categories: [
      { id: 'body', name: 'Thân van (Body)',          color: '#0891b2' },
      { id: 'act',  name: 'Actuator',                 color: '#dc2626' },
      { id: 'pos',  name: 'Positioner & Phụ kiện',    color: '#047857' },
      { id: 'fs',   name: 'Fail-safe & Kết nối',      color: '#d97706' },
    ],

    /* ──────────────────────────────────────────────────────────────────
       CONCEPTS: Click vào chip bất kỳ trong card để xem giải thích
    ────────────────────────────────────────────────────────────────── */
    concepts: {
      eq_pct:   { title:'Equal Percentage (% đồng đều)', e:'📈',
        body:'Mỗi % thay đổi độ mở → % thay đổi Cv bằng nhau so với giá trị hiện tại.\nCông thức: Cv = Cv_min × R^(lift/max_lift)  với R = rangeability (~50:1).\nDùng khi ΔP qua van thay đổi theo lưu lượng – phổ biến nhất trong vòng PID.',
        note:'Hầu hết Globe valve điều tiết tại NM Đạm Cà Mau dùng đặc tính Equal%.' },
      linear:   { title:'Linear Characteristic (Tuyến tính)', e:'📏',
        body:'Cv thay đổi tuyến tính với % độ mở: Cv = Cv_max × (lift / max_lift).\nDùng khi ΔP qua van gần như không đổi.\nÍt phổ biến hơn Equal% trong điều khiển PID.' },
      fast_op:  { title:'Fast Opening / Quick Opening (Mở nhanh)', e:'⚡',
        body:'Cv tăng rất nhanh ở những % mở đầu tiên (25% hành trình → ~80% Cv max).\nDùng cho van ON-OFF – không dùng trong vòng điều khiển PID.\nPhổ biến: Gate valve, Ball valve full-bore, Butterfly concentric.' },
      da:       { title:'Direct Acting (DA) – Tác động thuận', e:'⬇️',
        body:'Khí nén cấp vào PHÍA TRÊN màng diaphragm → áp tăng → stem ĐI XUỐNG.\nQuy tắc fail-safe:\n  DA + ATO (Air-To-Open)  = Fail-Close (FC)\n  DA + ATC (Air-To-Close) = Fail-Open  (FO)',
        note:'Fisher 657 là DA actuator phổ biến nhất tại NM Đạm Cà Mau.' },
      ra:       { title:'Reverse Acting (RA) – Tác động nghịch', e:'⬆️',
        body:'Khí nén cấp vào PHÍA DƯỚI màng diaphragm → áp tăng → stem ĐI LÊN.\nQuy tắc fail-safe:\n  RA + ATO = Fail-Open  (FO)\n  RA + ATC = Fail-Close (FC)',
        note:'Fisher 667 là RA actuator tại NM Đạm Cà Mau.' },
      sa:       { title:'Single Acting (SA) – Tác động đơn', e:'1️⃣',
        body:'Chỉ 1 phía được cấp khí nén; phía còn lại là lò xo hồi vị.\nƯu điểm: Fail-safe TỰ NHIÊN khi mất khí → lò xo đưa van về FC hoặc FO.\nDùng phổ biến cho Rack & Pinion actuator (van bi, bướm, nút).' },
      dbl_act:  { title:'Double Acting (DA) – Tác động kép', e:'2️⃣',
        body:'Cả 2 phía đều cấp khí nén luân phiên → lực lớn hơn, kiểm soát chính xác hơn.\nKHÔNG có lò xo hồi vị → KHÔNG tự fail-safe khi mất khí.\nCần thêm Trip valve 377 hoặc Lock-up valve để xử lý fail-safe.',
        note:'Piston Double Acting + Trip Valve 377: 3 chế độ FC / FL / FO.' },
      bench:    { title:'Bench Set – Thông số quan trọng nhất', e:'🔑',
        body:'Bench set = khoảng áp suất khí nén để actuator di chuyển đủ hành trình (0%→100%) TẠI XƯỞNG, khi CHƯA gắn body vào đường ống (không có áp process).\nVí dụ: DA 3–13 psi = cần 3 psi để bắt đầu, 13 psi để đạt 100% stroke.\nKhi lắp vào line, áp process tác động lên plug → lệch bench set → cần In-service adjustment.',
        note:'GT-ĐK-028: Bench set là thông số QUAN TRỌNG NHẤT của actuator diaphragm.' },
      deadband: { title:'Dead Band – Vùng chết', e:'🎯',
        body:'Dead band = dải tín hiệu vào mà van KHÔNG di chuyển, do ma sát cơ học trong packing và gland.\nĐơn vị: % tín hiệu điều khiển (0–100%).\nTypical: < 0.5% (positioner tốt), 2–5% (ma sát lớn).\nDead band lớn → gây dao động (hunting) trong vòng PID.\nGiảm bằng: positioner chất lượng cao + giảm lực kẹp packing.' },
      travel:   { title:'Travel – Hành trình van', e:'↕️',
        body:'Travel (stroke): Khoảng cách di chuyển thực tế của stem từ đóng hoàn toàn đến mở hoàn toàn.\nĐơn vị: inch hoặc mm  (1 inch = 25.4 mm).\nGT-ĐK-028 ví dụ:\n  Travel 3.5" = 3.5 × 25.4 = 88.9 ≈ 89 mm\n  Travel 1.5" = 1.5 × 25.4 = 38.1 ≈ 38 mm\nPositioner đo % travel để phản hồi vị trí thực tế về DCS.' },
      fc:       { title:'Fail-Close (FC) – Đóng khi sự cố', e:'🔒',
        body:'Van tự ĐÓNG khi mất nguồn khí nén hoặc tín hiệu.\nDùng cho: Van cấp NH₃, HC, hóa chất nguy hiểm.\nThực hiện qua lò xo actuator:\n  DA + ATO = FC\n  RA + ATC = FC' },
      fo:       { title:'Fail-Open (FO) – Mở khi sự cố', e:'🔓',
        body:'Van tự MỞ khi mất nguồn khí nén hoặc tín hiệu.\nDùng cho: Van bypass làm mát, van cấp steam, van quench.\nThực hiện qua lò xo:\n  DA + ATC = FO\n  RA + ATO = FO' },
      fl:       { title:'Fail-Last / Fail-Lock (FL) – Giữ vị trí', e:'🔐',
        body:'Van giữ nguyên vị trí cuối cùng khi mất tín hiệu điều khiển.\nThực hiện bằng: Lock-up valve (giữ áp trong actuator) hoặc Trip valve 377 chế độ FL.\nDùng khi cả đóng lẫn mở đều nguy hiểm.',
        note:'Trip valve 377 chế độ FL = bịt kín 2 ngõ C&F → giữ áp cả 2 phía cylinder.' },
      t377:     { title:'Trip Valve Fisher 377', e:'🔀',
        body:'Trip valve 3-way dùng cho Piston Double Acting (không có lò xo tự nhiên).\nTích hợp 2 air relay bên trong, điều khiển 2 cổng cylinder.\n3 chế độ đấu nối:\n  FC – Bình tích áp 1 ngõ → mất tín hiệu → van đóng\n  FL – Bịt kín 2 ngõ C&F  → giữ vị trí cuối\n  FO – Đảo ngược cổng C&F → mất tín hiệu → van mở',
        note:'GT-ĐK-028: Trip valve 377 tích hợp 2 air relay. Khác air relay đơn (chỉ 1 bộ 3 ngõ).' },
      lockup:   { title:'Lock-up Valve – Van giữ áp', e:'🔐',
        body:'Tự động KHÓA khí trong actuator khi áp supply giảm đột ngột → van giữ vị trí (Fail-Last FL).\nKhác Trip valve: Lock-up chỉ giữ áp, không chủ động đổi trạng thái.\nSetpoint: 20–100 PSIG.' },
      solenoid: { title:'Solenoid Valve – Van điện từ', e:'⚡',
        body:'Van điện từ ON-OFF nguồn khí cho actuator hoặc trip valve.\nNguyên lý: Cuộn dây điện từ → lực từ → plunger → đóng/mở.\nTín hiệu: 24 VDC / 110/230 VAC.\nDe-energize-to-trip (DET): mất điện → fail-safe position.\nDùng trong ESD/SIS cho van on-off quan trọng.' },
      lsb:      { title:'Limit Switch Box (LSB) – Hộp báo vị trí', e:'📡',
        body:'LSB lắp trên actuator để báo trạng thái OPEN / CLOSE về DCS hoặc ESD.\nGồm 2 switch: 1 báo OPEN, 1 báo CLOSE.\nTín hiệu ra: Dry contact (NO/NC) → DCS Digital Input.\nLoại: Micro-switch cơ hoặc Proximity switch (từ / điện dung).',
        note:'Van bướm 04HV-5003 (Tomoe) tại NM có LSB báo trạng thái về DCS.' },
      vball:    { title:'V-Ball Valve – Van Bi Chữ V', e:'🅥',
        body:'Ball valve với cạnh cắt hình chữ V trên ball.\nMục đích: Tạo đặc tính Equal% → cho phép ĐIỀU TIẾT (không chỉ ON-OFF).\nDùng Rack & Pinion + Positioner để điều khiển chính xác góc mở.\nLợi thế: Ít bị tắc với lưu chất nhớt, slurry, sợi.\nVí dụ: Fisher V500, V300.' },
      weir:     { title:'Weir Type – Van Màng Kiểu Gờ', e:'🌊',
        body:'Diaphragm valve có "weir" (gờ nhô cao) giữa thân van.\nMàng ép xuống weir để đóng van.\nCó thể điều tiết lưu lượng → cần positioner.\nStraight-through type: không có weir → chỉ ON-OFF.\nƯu: vệ sinh, không khoang chết, phù hợp ăn mòn/tiệt trùng.' },
      smart_pos:{ title:'Smart HART Positioner', e:'🧠',
        body:'Positioner kỹ thuật số giao tiếp qua HART protocol.\nTín hiệu vào:  4-20 mA + HART digital\nTín hiệu ra:   Khí nén 0.2–1 bar → actuator\nChức năng:\n  Auto-calibration, Valve diagnostics (valve signature),\n  Partial Stroke Test (PST), Dead band monitor.\nGiao tiếp HART cho phép đọc/ghi từ xa qua DCS/AMS.' },
      dvc6200:  { title:'Fisher DVC6200 – Smart HART Positioner', e:'🔬',
        body:'DVC6200 (Digital Valve Controller) = smart positioner phổ biến nhất tại NM Đạm Cà Mau.\nGiao thức: HART.\nPST (Partial Stroke Test): Kiểm tra ESD valve định kỳ mà không dừng quá trình.\nAMS Device Manager: Giám sát, cấu hình, chẩn đoán từ xa.',
        note:'DVC6200 lắp trên hầu hết Globe valve điều tiết quan trọng tại NM.' },
      f657:     { title:'Fisher 657 – Direct Acting Diaphragm Actuator', e:'⬇️',
        body:'Diaphragm actuator loại Direct Acting (DA) phổ biến nhất tại NM.\nKhí nén cấp TRÊN màng → stem đi XUỐNG khi áp tăng.\nDA + ATO = Fail-Close (FC)\nDA + ATC = Fail-Open  (FO)',
        note:'Fisher 657 + DVC6200 = cặp đôi phổ biến nhất tại NM Đạm Cà Mau.' },
      f667:     { title:'Fisher 667 – Reverse Acting Diaphragm Actuator', e:'⬆️',
        body:'Diaphragm actuator loại Reverse Acting (RA).\nKhí nén cấp DƯỚI màng → stem đi LÊN khi áp tăng.\nRA + ATO = Fail-Open  (FO)\nRA + ATC = Fail-Close (FC)' },
      rotork:   { title:'Rotork / Auma / Biffi – Electric Actuator (MOV)', e:'⚡',
        body:'3 hãng MOV chính tại NM Đạm Cà Mau:\n• Rotork (UK) – IQ3 series: ON-OFF & modulating, HART/Profibus\n• Auma (Germany) – SA/SAR series: robust, phổ biến công nghiệp nặng\n• Biffi (Italy): Chuyên van khí đường kính lớn\nTất cả đều có: Local/Remote selector, Torque limiter, Position feedback 4-20mA, Local panel.' },
      ih_cvt:   { title:'I/H Converter – Biến đổi dòng / thủy lực', e:'🔄',
        body:'I/H (Current-to-Hydraulic): Biến đổi 4-20 mA → áp suất dầu thủy lực.\nTương tự I/P nhưng đầu ra là dầu thủy lực (100–300 bar) thay vì khí nén.\nDùng cho Electrohydraulic actuator: Turbine governor, Compressor speed control.\nYêu cầu đáp ứng < 100 ms.' },
      torque:   { title:'Torque – Moment xoắn', e:'🔧',
        body:'Torque (Nm): Lực xoay của Rack & Pinion actuator để đóng/mở van quay.\nActuator phải có torque đủ lớn ở mọi điều kiện process.\nYếu tố ảnh hưởng: áp process (unbalanced force), ma sát packing, kích thước van.\nTypical safety factor: 1.25–1.5 × breakaway torque.\nSo sánh: Thrust (N) cho linear actuator; Torque (Nm) cho rotary.' },
      dashpot:  { title:'Dash-pot – Giảm chấn thủy lực', e:'🛡️',
        body:'Dash-pot: thiết bị giảm chấn thủy lực gắn trên đĩa check valve.\nMục đích: Giảm tốc độ đóng đĩa khi dòng chảy đảo chiều → tránh water hammer.\nNguyên lý: Piston trong cylinder dầu → dầu chảy qua orifice nhỏ → chậm lại.\nWater hammer: Sóng áp suất khi van đóng quá nhanh → nguy cơ vỡ đường ống.' },
      regulator:{ title:'Pressure Regulator – Bộ điều áp khí', e:'🌬️',
        body:'Air regulator ổn định áp suất khí supply cho positioner/actuator đúng bench set.\nThường: Giảm từ 6–7 bar (header) xuống 1.4 bar (positioner) hoặc 4 bar (actuator direct).\nTích hợp filter: Lọc dầu, nước, bụi bẩn trong khí nén.\nFisher 67D/67C tại NM.' },
      booster:  { title:'Volume Booster – Bộ khuếch đại lưu lượng', e:'💨',
        body:'Tăng lưu lượng khí đến actuator MÀ KHÔNG thay đổi áp suất.\nMục đích: Giảm stroke time của van lớn.\nTỷ lệ: 1:1 áp suất, nhưng lưu lượng × 5–10 lần.\nFisher 2625 tại NM.\nLắp song song với positioner output.' },
    },

    /* ──────────────────────────────────────────────────────────────────
       DATA: 17 mục – mỗi mục có cells[] (hiển thị thẻ) + goal/detail (popup)
    ────────────────────────────────────────────────────────────────── */
    data: [
      /* ========== THÂN VAN (BODY) – B1–B7 ========== */
      { id:0, stt:'B1', cat:'body', name:'Van cầu – Globe Valve', sub:'Sliding-stem · Equal% · Điều tiết chính xác',
        cells:[
          { l:'Chuyển động',         v:'Tịnh tiến (Sliding-stem)' },
          { l:'Đặc tính lưu lượng',  c:[{t:'Equal %',k:'eq_pct'},{t:'Linear',k:'linear'},{t:'Fast-opening',k:'fast_op'}] },
          { l:'Actuator thường dùng',c:[{t:'Diaphragm/Spring',k:'f657'},{t:'Piston (van lớn)',k:'dbl_act'}], w:1 },
          { l:'Positioner',          v:'✓ Bắt buộc – Smart / Analog I/P / Pneumatic' },
          { l:'Fail-safe',           c:[{t:'FC (Fail-Close)',k:'fc'},{t:'FO (Fail-Open)',k:'fo'}] },
          { l:'Ghi chú NM',          v:'Fisher GX/ED/EZ – Rangeability 50:1' },
        ],
        goal:'Van điều tiết phổ biến nhất tại NM Đạm Cà Mau (hãng Fisher). Kiểm soát lưu lượng chính xác liên tục. Dùng với positioner Smart/Analog I/P.',
        detail:'Cấu tạo: Thân hình cầu, stem trượt lên/xuống điều chỉnh orifice (sliding-stem). Dòng chảy đổi hướng qua thân.\nĐặc tính lưu lượng: Equal percentage (phổ biến nhất cho PID), Linear, Fast-opening.\nActuator: Diaphragm màng lò xo (DA/RA) hoặc Piston (van lớn).\nBắt buộc có POSITIONER để điều tiết chính xác.\nFail-safe: FC hoặc FO qua lò xo actuator.',
        equip:'Fisher GX, ED, EZ (tại NM)\nPositioner: Fisher DVC6200 (HART)',
        params:'Rangeability: 50:1\nChar: equal%, linear, fast-opening\nPositioner: BẮT BUỘC' },

      { id:1, stt:'B2', cat:'body', name:'Van cửa – Gate Valve', sub:'On-off · Full-bore · ΔP thấp · 04HV-2082',
        cells:[
          { l:'Chuyển động',  v:'Tịnh tiến (Nâng đĩa – gate)' },
          { l:'Mục đích',     v:'ON-OFF – KHÔNG điều tiết' },
          { l:'Đặc tính',     c:[{t:'Fast-opening',k:'fast_op'},{t:'Full-bore ΔP≈0'}] },
          { l:'Actuator',     c:[{t:'Tay quay (manual)'},{t:'Piston',k:'dbl_act'},{t:'Rack & Pinion',k:'torque'},{t:'MOV',k:'rotork'}], w:1 },
          { l:'Positioner',   v:'✗ Không cần (ON-OFF)' },
          { l:'Ghi chú NM',   v:'04HV-2082 tại NM Đạm Cà Mau' },
        ],
        goal:'Đóng/mở hoàn toàn (on-off). Tổn thất áp suất thấp nhất khi mở hoàn toàn (full-bore). Chủ yếu tay quay, tự động dùng Piston/Rack & Pinion.',
        detail:'Cấu tạo: Gate (tấm chắn) trượt vuông góc với dòng chảy. Chỉ ở vị trí đóng hoàn toàn hoặc mở hoàn toàn.\nFull-bore: đường kính trong = đường kính ống → ΔP ≈ 0 khi mở.\nActuator: Chủ yếu TAY QUAY. Tự động: Piston, Rack & Pinion, Electric (Rotork, Auma).\nKHÔNG cần positioner (van on-off).',
        equip:'04HV-2082 (tại NM)\nWedge gate, Parallel slide\nActuator: Piston / Rack & Pinion / Rotork, Auma',
        params:'Char: Fast-opening\nFull-bore: ΔP ≈ 0 khi mở\nChỉ On-off, KHÔNG điều tiết\nKhông cần Positioner' },

      { id:2, stt:'B3', cat:'body', name:'Van nút – Plug Valve', sub:'Xoay 90° · 2-way / 3-way · Chuyển hướng dòng',
        cells:[
          { l:'Chuyển động',  v:'Xoay 90° (Rotary)' },
          { l:'Mục đích',     v:'ON-OFF hoặc chuyển hướng dòng 3-way' },
          { l:'Actuator',     c:[{t:'Tay quay (manual)'},{t:'Rack & Pinion',k:'torque'},{t:'MOV',k:'rotork'}], w:1 },
          { l:'Positioner',   v:'✗ Không cần (ON-OFF)' },
          { l:'Fail-safe',    c:[{t:'Single acting FC/FO',k:'sa'},{t:'Double acting + Trip 377',k:'t377'}], w:1 },
        ],
        goal:'Đóng/mở nhanh hoặc chuyển hướng dòng chảy (3-way mix/divert). Cấu trúc đơn giản. Chủ yếu tay quay, tự động dùng Rack & Pinion/Electric.',
        detail:'Cấu tạo: Plug hình trụ/côn có lỗ xoay 90° trong thân.\nLoại: 2-way (on-off), 3-way (phân phối hoặc trộn 2 dòng).\nActuator: Chủ yếu TAY QUAY. Tự động: Rack & Pinion hoặc Electric.\nKHÔNG cần positioner. Không dùng điều tiết.',
        equip:'2-way Plug valve\n3-way Plug valve (mix/divert)\nActuator: Rack & Pinion / Electric',
        params:'Stroke: 90°\nChar: Fast-opening\n3-way: mix hoặc divert\nKhông cần Positioner' },

      { id:3, stt:'B4', cat:'body', name:'Van bi – Ball Valve', sub:'Xoay 90° · On-off nhanh · V-ball điều tiết · Rotork/Auma/Biffi',
        cells:[
          { l:'Chuyển động',  v:'Xoay 90° (Rotary)' },
          { l:'Phân loại',    c:[{t:'Full Bore – ON-OFF'},{t:'V-ball – Điều tiết',k:'vball'}] },
          { l:'Actuator',     c:[{t:'Rack & Pinion (ON-OFF)',k:'torque'},{t:'MOV Rotork/Auma/Biffi',k:'rotork'}], w:1 },
          { l:'Positioner',   v:'Chỉ khi dùng V-ball điều tiết' },
          { l:'Fail-safe',    c:[{t:'Single acting FC/FO',k:'sa'},{t:'Double acting + Trip 377',k:'t377'},{t:'MOV + UPS',k:'rotork'}], w:1 },
        ],
        goal:'On-off nhanh, kín tốt. V-ball dùng điều tiết lưu chất nhớt/slurry. Actuator phổ biến: Rack & Pinion. Electric: Rotork, Auma, Biffi tại NM.',
        detail:'Cấu tạo: Ball hình cầu có lỗ xoay 90° giữa 2 vòng làm kín.\nFull-bore ball: đường kính lỗ = đường ống → on-off, fast-opening.\nV-ball (V-notch): đặc tính equal percentage → điều tiết slurry, nhớt.\nActuator: Rack & Pinion (phổ biến nhất, 90° rotary). Electric: Rotork, Auma, Biffi.\nPositioner: CHỈ dùng khi V-ball điều tiết.',
        equip:'Full-bore Ball (on-off)\nFisher V500, V300 (V-ball)\nRack & Pinion (Single/Double acting)\nRotork, Auma, Biffi (Electric MOV)',
        params:'Char: Fast-opening (full-bore)\nChar: Equal% (V-ball)\nPositioner: CHỈ khi V-ball\nLeakage: Class IV-VI' },

      { id:4, stt:'B5', cat:'body', name:'Van bướm – Butterfly Valve', sub:'Xoay 90° · Rack & Pinion · Tomoe 04HV-5003 · LSB',
        cells:[
          { l:'Chuyển động',  v:'Xoay 90° (Rotary – Disc)' },
          { l:'Loại',         c:[{t:'Concentric (ON-OFF)'},{t:'Double/Triple-eccentric (điều tiết)'}] },
          { l:'Actuator',     c:[{t:'Rack & Pinion Tomoe',k:'torque'},{t:'MOV Rotork/Auma',k:'rotork'}], w:1 },
          { l:'Positioner',   v:'Khi dùng điều tiết (triple eccentric)' },
          { l:'Phụ kiện',     c:[{t:'Limit Switch Box LSB',k:'lsb'},{t:'Solenoid valve',k:'solenoid'}] },
          { l:'Ghi chú NM',   v:'Hãng Tomoe – 04HV-5003, Rack & Pinion' },
        ],
        goal:'Tiết kiệm chi phí ống lớn. On-off và điều tiết thô. Actuator Rack & Pinion (Tomoe). Có Limit Switch Box báo trạng thái.',
        detail:'Cấu tạo: Disc hình đĩa xoay 90° quanh trục giữa trong thân.\nLoại: Concentric (fast-opening, kín kém), Double-eccentric, Triple-eccentric (metal-to-metal, equal%, PN cao).\nActuator: Rack & Pinion (Tomoe, 04HV-5003): Single hoặc Double acting.\nLimit Switch Box: báo trạng thái ON/OFF về DCS/ESD.',
        equip:'04HV-5003 – Tomoe (Rack & Pinion, NM)\nLimit Switch Box (LSB)\nRotork, Auma (Electric option)',
        params:'Stroke: 90°\nChar: Fast-opening (concentric)\nDN lớn ≥ DN100\nLSB báo trạng thái về DCS' },

      { id:5, stt:'B6', cat:'body', name:'Van màng – Diaphragm Valve', sub:'Lưu chất ăn mòn · Diaphragm actuator · ITT',
        cells:[
          { l:'Chuyển động',  v:'Tịnh tiến (Màng cao su/PTFE)' },
          { l:'Phân loại',    c:[{t:'Weir type (điều tiết)',k:'weir'},{t:'Straight-through (ON-OFF)'}] },
          { l:'Actuator',     c:[{t:'Diaphragm actuator (ITT)',k:'f657'}], w:1 },
          { l:'Positioner',   v:'Khi điều tiết Weir type' },
          { l:'Ứng dụng',     v:'Lưu chất ăn mòn, bùn, vô trùng – không packing' },
        ],
        goal:'Phù hợp lưu chất ăn mòn, hóa chất. Không tiếp xúc lưu chất và cơ cấu truyền động. Actuator Diaphragm màng lò xo. ITT tại NM.',
        detail:'Cấu tạo: Màng đàn hồi ép lên saddle/weir để chặn dòng. Không có packing tiếp xúc lưu chất.\nLoại: Weir type (tác động thẳng, có thể điều tiết), Straight-through.\nActuator: Diaphragm actuator DA, áp suất 2-7 bar.\nTại NM: hãng ITT với diaphragm actuator.',
        equip:'ITT Diaphragm Valve (tại NM)\nWeir type, Straight-through\nActuator: Diaphragm DA\nLining: PTFE, Rubber, EPDM',
        params:'Char: Linear (Weir type)\nPN thấp < 16 bar\nActuator: Diaphragm 2-7 bar' },

      { id:6, stt:'B7', cat:'body', name:'Van một chiều – Check Valve', sub:'Thụ động · Không cần actuator · Bảo vệ bơm/máy nén',
        cells:[
          { l:'Nguyên lý',     v:'Tự động theo áp suất dòng chảy (passive valve)' },
          { l:'Actuator',      v:'✗ KHÔNG CÓ – Van hoàn toàn thụ động' },
          { l:'Hỗ trợ thêm',  c:[{t:'Lò xo tăng lực đóng'},{t:'Dash-pot giảm sốc',k:'dashpot'},{t:'Counter-weight'}], w:1 },
          { l:'Ứng dụng',      v:'Ngăn dòng ngược – bảo vệ bơm/máy nén' },
        ],
        goal:'Tự động cho phép dòng chảy một chiều. Ngăn dòng ngược bảo vệ bơm, máy nén. Không cần actuator hay tín hiệu điều khiển.',
        detail:'Nguyên lý: Disc/ball/plate mở tự động khi áp xuôi > cracking pressure. Đóng tự động khi dòng ngược.\nLOẠI VAN THỤ ĐỘNG – KHÔNG CÓ actuator.\nLoại: Swing check, Lift check, Dual-plate (wafer), Piston check.\nHỗ trợ: lò xo (tăng lực đóng), dash-pot (giảm sốc), counter-weight.',
        equip:'Swing check (horizontal)\nDual-plate wafer check\nLift check (vertical upward)\nKHÔNG CÓ actuator',
        params:'Không cần actuator\nTự động theo dòng chảy\nCracking pressure: 0.05-0.5 bar' },

      /* ========== ACTUATOR – A1–A5 ========== */
      { id:7, stt:'A1', cat:'act', name:'Actuator Màng Lò Xo – Diaphragm/Spring', sub:'DA / RA · 2–7 bar · Fail-safe lò xo · Fisher 657/667',
        cells:[
          { l:'Nguyên lý',          v:'Khí nén → màng cao su → thắng lực lò xo → di chuyển stem' },
          { l:'Áp suất supply',     v:'2 – 7 bar (30 – 100 psi)' },
          { l:'Kiểu tác động',      c:[{t:'Direct Acting (DA)',k:'da'},{t:'Reverse Acting (RA)',k:'ra'}] },
          { l:'Thông số kỹ thuật',  c:[{t:'Bench Set',k:'bench'},{t:'Dead Band',k:'deadband'},{t:'Travel',k:'travel'}], w:1 },
          { l:'Hãng tại NM',        c:[{t:'Fisher 657 (DA)',k:'f657'},{t:'Fisher 667 (RA)',k:'f667'}] },
          { l:'Dùng với',           v:'Globe valve, Diaphragm valve (điều tiết)' },
        ],
        goal:'Phổ biến nhất cho van cầu Globe tại NM. Fail-safe tự nhiên nhờ lò xo. Đơn giản, bền, ít bảo trì.',
        detail:'Nguyên lý: Khí nén đẩy màng → thắng lực lò xo → dịch chuyển stem.\nDA (Fisher 657): Khí cấp phía TRÊN màng → stem đi XUỐNG.\nRA (Fisher 667): Khí cấp phía DƯỚI màng → stem đi LÊN.\nBench set: khoảng áp để đóng/mở hoàn toàn tại xưởng.\nDead band: khoảng hành trình không thay đổi do ma sát packing.\nFail-safe: Mất khí → lò xo → FC hoặc FO.',
        equip:'Fisher 657 (DA)\nFisher 667 (RA)\nFisher 1051, 1052 (rotary)',
        params:'Áp lực: 2-7 bar (30-100 psi)\nBench set: 3-13 (DA) / 5-15 (RA) psi\nFail-safe: tự nhiên nhờ lò xo' },

      { id:8, stt:'A2', cat:'act', name:'Actuator Rack & Pinion', sub:'Xoay 90° · Van bi/bướm/nút · Single/Double acting · Tomoe',
        cells:[
          { l:'Nguyên lý',      v:'Khí → piston tịnh tiến → rack & pinion → xoay 90°' },
          { l:'Góc xoay',       v:'0° – 90° (Quarter-turn)' },
          { l:'Kiểu tác động',  c:[{t:'Single Acting – SA',k:'sa'},{t:'Double Acting – DA',k:'dbl_act'}], w:1 },
          { l:'Fail-safe SA',   c:[{t:'FC (Fail-Close)',k:'fc'},{t:'FO (Fail-Open)',k:'fo'}] },
          { l:'Fail-safe DA',   c:[{t:'Trip valve 377',k:'t377'},{t:'hoặc Lock-up',k:'lockup'}] },
          { l:'Dùng với',       v:'Ball, Butterfly, Plug valve (rotary 90°)' },
        ],
        goal:'Actuator xoay 90° cho van bi, van bướm, van nút. Chuyển đổi chuyển động thẳng thành xoay qua cơ cấu bánh răng.',
        detail:'Nguyên lý: Piston khí nén di chuyển thẳng → rack & pinion chuyển thành xoay 90°.\nSingle acting: 1 phía khí + lò xo đối nghịch → fail-safe tự nhiên (FC hoặc FO).\nDouble acting: 2 phía khí thay nhau → lực lớn hơn, không fail-safe tự nhiên → cần trip valve 377.\nTomoe (tại NM): van bướm 04HV-5003.',
        equip:'Tomoe (04HV-5003 tại NM)\nSMC, Rotork, Festo\nSingle acting: fail-safe lò xo\nDouble acting: cần trip valve 377',
        params:'Stroke: 90° (rotary)\nSingle acting: FC hoặc FO\nDouble acting: cần trip valve\nDùng cho Ball/Butterfly/Plug' },

      { id:9, stt:'A3', cat:'act', name:'Actuator Piston – Lực lớn', sub:'≤10 bar · Linear & Rotary · Double acting · Van lớn',
        cells:[
          { l:'Nguyên lý',      v:'Khí nén → piston trong cylinder thép → stem' },
          { l:'Áp suất',        v:'Đến 10 bar (150 psi) – Cao hơn Diaphragm nhiều' },
          { l:'Kiểu tác động',  c:[{t:'Single Acting (lò xo hồi)',k:'sa'},{t:'Double Acting (lực tối đa)',k:'dbl_act'}], w:1 },
          { l:'Fail-safe DA',   c:[{t:'Trip valve 377',k:'t377'},{t:'Volume tank bình tích áp'}] },
          { l:'Dùng với',       v:'Globe valve lớn (>4"), Gate valve tự động hóa' },
          { l:'Ưu điểm',        v:'Lực lớn hơn diaphragm, áp cao, hành trình dài' },
        ],
        goal:'Lực nâng lớn hơn nhiều so với diaphragm. Dùng cho van cầu lớn, van cửa lớn, áp suất công nghệ cao.',
        detail:'Nguyên lý: Khí nén tác động lên piston trong cylinder thép → chuyển động thẳng.\nSingle acting: lò xo trả về → có fail-safe. Double acting: khí 2 phía → lực lớn nhất → KHÔNG fail-safe tự nhiên → cần trip valve 377 + volume tank.\nScotch-yoke: piston linear → xoay 90° cho ball/butterfly lớn.',
        equip:'Fisher 585C, 685 (linear piston)\nFisher 1080 (scotch-yoke rotary)\nTrip valve 377 cho double acting\nVolume tank (bình tích áp)',
        params:'Áp lực: đến 10 bar (150 psi)\nDouble acting: lực lớn nhất\nSingle acting: lực + fail-safe lò xo' },

      { id:10, stt:'A4', cat:'act', name:'Actuator Electrohydraulic', sub:'Governor máy nén · Fisher · Đáp ứng nhanh ms',
        cells:[
          { l:'Nguyên lý',          v:'Motor điện → bơm dầu thủy lực → cylinder → stem' },
          { l:'Tín hiệu điều khiển',c:[{t:'I/H Converter (4-20mA → dầu)',k:'ih_cvt'}], w:1 },
          { l:'Đáp ứng',            v:'< 100 ms – Nhanh nhất trong các loại actuator' },
          { l:'Dùng với',           v:'Turbine governor, Compressor suction throttle' },
          { l:'Nhược điểm',         v:'Phức tạp, cần hệ thống dầu riêng, bảo trì cao' },
        ],
        goal:'Điều khiển van governor của máy nén tốc độ cao. Đáp ứng cực nhanh (milliseconds), lực lớn, độ chính xác cao.',
        detail:'Nguyên lý: Bơm thủy lực điện tử + servo valve (I/H converter) điều khiển dầu thủy lực → tác động lên piston → dịch chuyển stem.\nI/H converter: chuyển đổi tín hiệu điện sang thủy lực.\nỨng dụng: van governor (speed control) của máy nén NH₃, CO₂ tại NM – cần đáp ứng ms.',
        equip:'Fisher Electrohydraulic Actuator\nI/H Converter (điện → thủy lực)\nBơm thủy lực tích hợp\nServo valve điều khiển dầu',
        params:'Đáp ứng: < 100 ms\nLực: rất lớn (thủy lực)\nDùng cho governor van máy nén' },

      { id:11, stt:'A5', cat:'act', name:'Actuator Motor Điện – MOV', sub:'Rotork · Auma · Biffi · 24V–380VAC · Không cần khí nén',
        cells:[
          { l:'Nguyên lý',       v:'Motor điện → hộp số giảm tốc → xoay stem/shaft' },
          { l:'Nguồn điện',      v:'24 VDC / 110–230 VAC / 380 VAC 3-pha' },
          { l:'Kiểu vận hành',   c:[{t:'ON-OFF'},{t:'Modulating (điều tiết)'}] },
          { l:'Hãng tại NM',     c:[{t:'Rotork IQ3/AQ',k:'rotork'},{t:'Auma SA/SAR',k:'rotork'},{t:'Biffi',k:'rotork'}] },
          { l:'Fail-safe',       v:'Cần UPS hoặc spring-return module' },
          { l:'Dùng với',        v:'Gate, Ball, Butterfly, Plug valve' },
        ],
        goal:'Dùng cho khu vực không có khí nén. Tích hợp bus truyền thông HART/Profibus. Rotork, Auma, Biffi tại NM.',
        detail:'Nguyên lý: Motor điện AC/DC + hộp số → xoay (part-turn 90°) hoặc nhiều vòng (multi-turn).\nLoại: Multi-turn: gate, globe. Part-turn: ball, butterfly, plug (90°).\nHãng tại NM: Rotork, Auma, Biffi.\nFail-safe: không tự nhiên → cần UPS hoặc spring-return.',
        equip:'Rotork IQ3, AQ (multi-turn, part-turn)\nAuma SAR, SA (AC 3-pha)\nBiffi (part-turn)',
        params:'Nguồn: 24VDC / 110-380VAC\nTốc độ: 10-60 s/stroke\nComm: HART, Profibus, Modbus\nFail-safe: cần UPS hoặc spring-return' },

      /* ========== POSITIONER & PHỤ KIỆN – P1–P3 ========== */
      { id:12, stt:'P1', cat:'pos', name:'Positioner – Bộ định vị van', sub:'3 loại: Pneumatic · Analog I/P · Smart HART/FF · Fisher DVC6200',
        cells:[
          { l:'Chức năng',      v:'PID vòng kín thứ 2: SP = tín hiệu DCS, PV = vị trí van, MV = áp khí actuator' },
          { l:'3 loại',         c:[{t:'Smart HART/FF',k:'smart_pos'},{t:'Analog I/P (4-20mA→khí)'},{t:'Pneumatic (3-15psi→khí)'}], w:1 },
          { l:'Hãng tại NM',    c:[{t:'Fisher DVC6200',k:'dvc6200'}] },
          { l:'Cần cho van nào',v:'✓ Van điều tiết (Globe). ✗ Không cần van ON-OFF' },
          { l:'Tín hiệu ra',    v:'Khí nén 0.2–1 bar (3–15 psi) → Actuator' },
        ],
        goal:'Điều chỉnh vị trí van chính xác theo tín hiệu điều khiển. Hoạt động như PID thứ 2.',
        detail:'KHÁI NIỆM: Positioner so sánh vị trí thực van (cảm biến) với setpoint từ DCS → điều chỉnh áp khí cấp/xả actuator → đưa van về vị trí chính xác.\n3 LOẠI:\n1. Pneumatic: in 3-15 psi → out 3-15 psi. Cổ điển.\n2. Analog I/P: in 4-20mA → out 3-15 psi.\n3. Smart/Digital: 4-20mA + HART/FF. Tự chẩn đoán, giao tiếp DCS/AMS.',
        equip:'Fisher DVC6200 (Smart HART, tại NM)\nFisher 3582 (pneumatic)\nSiemens SIPART PS2',
        params:'Pneumatic: 3-15 psi → 3-15 psi\nAnalog I/P: 4-20mA → 3-15 psi\nSmart: HART / FF / Profibus PA' },

      { id:13, stt:'P2', cat:'pos', name:'Regulator · Volume Booster · I/P Converter', sub:'Điều áp · Khuếch đại lưu lượng · Chuyển đổi tín hiệu',
        cells:[
          { l:'Regulator (Fisher 67D)',      c:[{t:'Ổn định áp supply → đúng Bench Set',k:'regulator'}] },
          { l:'Volume Booster (Fisher 2625)',c:[{t:'Tăng lưu lượng khí → Stroke nhanh hơn',k:'booster'}] },
          { l:'I/P Converter (Fisher 546)',  v:'4-20mA → 3-15 psi  (open-loop, không feedback vị trí)' },
          { l:'Khi nào dùng',               v:'Regulator: tất cả actuator. Booster: van lớn. I/P: van on-off / van cũ' },
        ],
        goal:'Regulator cài đặt áp nguồn khí đúng bench set. Volume Booster tăng tốc độ đáp ứng van lớn.',
        detail:'REGULATOR (Fisher 67D/67C): Điều áp supply → đúng bench set. Tích hợp filter lọc dầu/nước.\nVOLUME BOOSTER (Fisher 2625): Khuếch đại lưu lượng, 1:1 áp suất, lưu lượng ×5-10 lần.\nI/P CONVERTER (Fisher 546): 4-20mA → 3-15 psi open-loop. Dùng thay positioner cho van on-off/cũ.',
        equip:'Fisher 67D, 67C (Regulator)\nFisher 2625, 2625NS (Volume Booster)\nFisher 546, 546E (I/P Converter)',
        params:'Regulator: ổn áp 20-100 PSIG\nBooster: tăng Cv lưu lượng khí\nI/P: 4-20mA → 3-15 psi open-loop' },

      { id:14, stt:'P3', cat:'pos', name:'Lock-up · Air Relay · Trip Valve 377 · Solenoid · LSB', sub:'Phụ kiện an toàn và giám sát vị trí van',
        cells:[
          { l:'Lock-up Valve',  c:[{t:'Giữ vị trí khi mất khí – FL',k:'lockup'}] },
          { l:'Trip Valve 377', c:[{t:'FC / FL / FO cho Piston DA',k:'t377'}] },
          { l:'Solenoid Valve', c:[{t:'ON-OFF khí nén theo tín hiệu điện',k:'solenoid'}] },
          { l:'Limit Switch Box',c:[{t:'Báo OPEN/CLOSE về DCS/ESD',k:'lsb'}] },
          { l:'Air Relay',      v:'Chuyển hướng tín hiệu khí – 3 ngõ (1, 2, 3)' },
        ],
        goal:'Các phụ kiện đảm bảo fail-safe (lock-up, trip valve 377), on-off nhanh (solenoid), giám sát vị trí (LSB).',
        detail:'LOCK-UP VALVE: Giữ khí trong actuator khi mất áp nguồn → van giữ vị trí (FL).\nAIR RELAY: 3 ngõ, chuyển hướng tín hiệu khí khi có/mất air signal.\nTRIP VALVE FISHER 377: Tích hợp 2 air relay, dùng cho piston double acting. 3 chế độ: FC, FL, FO.\nSOLENOID VALVE: De-energize = fail-safe.\nLIMIT SWITCH BOX: Báo vị trí đóng/mở về DCS/ESD (DI).',
        equip:'Fisher 377 Trip Valve (piston DA)\nBifold SPR-08 (Air Relay)\nASCO, Parker (Solenoid)\nTopwork LSB (tại NM)',
        params:'Lock-up: FL giữ vị trí\n377: FC/FL/FO cho piston DA\nSolenoid: de-energ = fail\nLSB: DI → DCS/ESD feedback' },

      /* ========== FAIL-SAFE & KẾT NỐI – F1–F2 ========== */
      { id:15, stt:'F1', cat:'fs', name:'Fail-safe: DA/RA × ATC/ATO → FC/FO/FL', sub:'Ma trận vị trí an toàn khi mất tín hiệu',
        cells:[
          { l:'Actuator action',c:[{t:'DA: áp↑ → stem xuống',k:'da'},{t:'RA: áp↑ → stem lên',k:'ra'}] },
          { l:'Kết hợp → FC', c:[{t:'DA + ATO = FC',k:'fc'},{t:'RA + ATC = FC',k:'fc'}] },
          { l:'Kết hợp → FO', c:[{t:'DA + ATC = FO',k:'fo'},{t:'RA + ATO = FO',k:'fo'}] },
          { l:'Kết hợp → FL', c:[{t:'Piston DA + Lock-up',k:'fl'},{t:'Piston DA + Trip 377',k:'t377'}] },
          { l:'Dùng FC cho',   v:'Lưu chất nguy hiểm: NH₃, HC, hóa chất độc' },
          { l:'Dùng FO cho',   v:'Làm mát, quench, cấp steam bảo vệ' },
        ],
        goal:'Xác định vị trí van khi mất tín hiệu, khí nén hoặc điện. Thiết kế fail-safe theo yêu cầu an toàn (SIL, HAZOP).',
        detail:'ACTUATOR ACTION:\n• DA: áp tăng → stem xuống. RA: áp tăng → stem lên.\nBODY ACTION:\n• ATC (Air-To-Close): cấp khí → đóng. ATO (Air-To-Open): cấp khí → mở.\nKẾT HỢP:\n• DA + ATO = FC; RA + ATC = FC.\n• DA + ATC = FO; RA + ATO = FO.\n• Piston DA + Lock-up = FL.',
        equip:'Lò xo trong actuator (FC/FO)\nLock-up Valve (FL)\nFisher 377 Trip Valve (FL/FC/FO piston DA)',
        params:'FC: dòng nguy hiểm (NH₃, HC)\nFO: làm mát / quench / steam\nFL: giữ vị trí, cần lock-up\nFisher 377: 3 chế độ đấu nối' },

      { id:16, stt:'F2', cat:'fs', name:'Vòng lặp điều khiển P&ID & Ký hiệu van', sub:'Control Loop · FT→FIC→FY→van→FT · Ký hiệu ISA',
        cells:[
          { l:'Vòng lặp FIC', v:'FT → 4-20mA → DCS (FIC) → 4-20mA → Positioner → Khí → Actuator → Van → FT', w:1 },
          { l:'Ký hiệu P&ID', c:[{t:'FC – Đóng khi sự cố',k:'fc'},{t:'FO – Mở khi sự cố',k:'fo'},{t:'FL – Giữ vị trí',k:'fl'}], w:1 },
          { l:'Solenoid ký hiệu',c:[{t:'2-way NC/NO',k:'solenoid'},{t:'3-way P-E-C',k:'solenoid'},{t:'4-way P-E-A-B',k:'solenoid'}], w:1 },
          { l:'FY / PY',      v:'FY = I/P Converter; PY = Positioner output trên P&ID' },
        ],
        goal:'Hiểu vòng lặp điều khiển hoàn chỉnh qua van trên P&ID. Đọc ký hiệu van FC/FO/FL và symbol solenoid theo ISA.',
        detail:'VÒNG LẶP:\n• FT → DCS (FIC) → 4-20mA → FY (I/P) → 3-15 psi → Positioner → Khí → Actuator → Van → FT.\nKÝ HIỆU P&ID:\n• FC: mất tín hiệu → đóng.\n• FO: mất tín hiệu → mở.\n• FL: mất tín hiệu → giữ nguyên.',
        equip:'FT: transmitter lưu lượng\nFIC: controller DCS\nFY: I/P converter\nPositioner (DVC6200)',
        params:'DCS out: 4-20mA → FY (I/P)\nI/P: 3-15 psi → positioner\nPositioner: feedback + điều chỉnh' },
    ],

    /* ─── MINDMAP (giữ nguyên) ─── */
    mindmap: {
      nodes: [
        { id:'globe',     x:30,  y:48,  w:190, h:48, label:'Van cầu (Globe)\nEqual% · DA/RA · Fisher', cat:'body', sub:'product' },
        { id:'gate',      x:30,  y:112, w:190, h:44, label:'Van cửa (Gate)\nOn-off · Full-bore · 04HV-2082', cat:'body' },
        { id:'ball',      x:30,  y:172, w:190, h:44, label:'Van bi (Ball)\nR&P · V-ball · Rotork', cat:'body' },
        { id:'butterfly', x:30,  y:232, w:190, h:44, label:'Van bướm (Butterfly)\nTomoe · R&P · 04HV-5003', cat:'body' },
        { id:'plug',      x:30,  y:292, w:190, h:44, label:'Van nút (Plug)\nXoay 90° · 3-way', cat:'body' },
        { id:'diaphm',    x:30,  y:352, w:190, h:44, label:'Van màng (Diaphragm)\nĂn mòn · ITT', cat:'body' },
        { id:'check',     x:30,  y:412, w:190, h:44, label:'Van 1 chiều (Check)\nThụ động · Không actuator', cat:'body' },
        { id:'spr',    x:285, y:62,  w:200, h:62, label:'Diaphragm/Spring\nDA 657 · RA 667 · 2-7 bar\nFail-safe lò xo tự nhiên', cat:'act', sub:'product' },
        { id:'rp',     x:285, y:152, w:200, h:55, label:'Rack & Pinion\nXoay 90° · Single/Double\nBall · Butterfly · Plug', cat:'act' },
        { id:'piston', x:285, y:230, w:200, h:55, label:'Piston Actuator\n≤10 bar · Lực lớn\nDouble: cần trip valve', cat:'act' },
        { id:'eh',     x:285, y:313, w:200, h:52, label:'Electrohydraulic\nGovernor máy nén\nFisher · I/H · Nhanh ms', cat:'act' },
        { id:'mov',    x:285, y:386, w:200, h:55, label:'Electric Motor (MOV)\nRotork · Auma · Biffi\n24V-380VAC · Không khí', cat:'act' },
        { id:'smart',  x:555, y:48,  w:190, h:58, label:'Smart Positioner\nHART · FF · Profibus\nFisher DVC6200 (NM)', cat:'pos', sub:'product' },
        { id:'ip',     x:555, y:132, w:190, h:44, label:'Analog I/P\n4-20mA → 3-15 psi\nFisher 546', cat:'pos' },
        { id:'pneu',   x:555, y:192, w:190, h:44, label:'Pneumatic Positioner\n3-15 psi → 3-15 psi\nFisher 3582', cat:'pos' },
        { id:'reg',    x:555, y:254, w:190, h:44, label:'Regulator\nĐiều áp bench set\nFisher 67D/67C', cat:'pos' },
        { id:'boost',  x:555, y:314, w:190, h:44, label:'Volume Booster\nKhuếch đại lưu lượng\nFisher 2625', cat:'pos' },
        { id:'sv',     x:555, y:374, w:190, h:44, label:'Solenoid Valve\n24VDC · 2/3/4-way\nDe-energ = fail', cat:'pos' },
        { id:'lsb',    x:555, y:430, w:190, h:44, label:'Limit Switch Box\nOpen/Close DI\nTopwork (NM)', cat:'pos' },
        { id:'fc',    x:820, y:62,  w:190, h:52, label:'FC – Fail Close\nDA+ATO hoặc RA+ATC\nDòng nguy hiểm NH₃/HC', cat:'fs' },
        { id:'fo',    x:820, y:142, w:190, h:52, label:'FO – Fail Open\nDA+ATC hoặc RA+ATO\nLàm mát · Quench', cat:'fs' },
        { id:'fl',    x:820, y:222, w:190, h:52, label:'FL – Fail Last\nPiston + Lock-up\nGiữ vị trí cuối', cat:'fs' },
        { id:'t377',  x:820, y:306, w:190, h:55, label:'Trip Valve 377\n2 Air Relay tích hợp\nFC / FL / FO cho Piston', cat:'fs' },
        { id:'loop',  x:1080, y:155, w:210, h:90, label:'Control Loop\nFT→FIC→FY→POS\n→ACT→VAN→FT\nDCS PID 4-20mA', cat:'fs', sub:'product' },
      ],
      edges: [
        { from:'globe',     to:'spr',    color:'blue',   label:'DA/RA' },
        { from:'globe',     to:'piston', color:'blue',   label:'Van lớn' },
        { from:'gate',      to:'rp',     color:'cyan',   label:'R&P' },
        { from:'gate',      to:'piston', color:'cyan' },
        { from:'ball',      to:'rp',     color:'cyan',   label:'R&P phổ biến' },
        { from:'ball',      to:'mov',    color:'purple', label:'Rotork/Auma' },
        { from:'butterfly', to:'rp',     color:'cyan',   label:'Tomoe' },
        { from:'butterfly', to:'mov',    color:'purple' },
        { from:'plug',      to:'rp',     color:'cyan' },
        { from:'diaphm',    to:'spr',    color:'blue' },
        { from:'spr',    to:'smart',  color:'green', label:'Positioner' },
        { from:'spr',    to:'ip',     color:'green' },
        { from:'spr',    to:'pneu',   color:'green' },
        { from:'piston', to:'smart',  color:'green' },
        { from:'piston', to:'t377',   color:'amber', label:'Fail-safe' },
        { from:'rp',     to:'sv',     color:'orange', label:'On-off' },
        { from:'mov',    to:'smart',  color:'green', label:'HART' },
        { from:'reg',    to:'spr',    color:'gray',  dashed:true, label:'Ổn áp' },
        { from:'boost',  to:'spr',    color:'gray',  dashed:true, label:'Tăng lưu lượng' },
        { from:'sv',     to:'spr',    color:'orange' },
        { from:'sv',     to:'rp',     color:'orange' },
        { from:'lsb',    to:'loop',   color:'green', label:'DI feedback' },
        { from:'spr',  to:'fc',    color:'gray', dashed:true, label:'Lò xo FC' },
        { from:'spr',  to:'fo',    color:'gray', dashed:true, label:'Lò xo FO' },
        { from:'t377', to:'fc',    color:'amber', label:'Đấu nối FC' },
        { from:'t377', to:'fl',    color:'amber', label:'Đấu nối FL' },
        { from:'t377', to:'fo',    color:'amber' },
        { from:'smart', to:'loop', color:'blue',  label:'4-20mA' },
        { from:'fc',    to:'loop', color:'gray',  dashed:true },
        { from:'fo',    to:'loop', color:'gray',  dashed:true },
        { from:'fl',    to:'loop', color:'gray',  dashed:true },
      ],
      zones: [
        { x:15,   y:30,  w:225, h:448, label:'THÂN VAN (BODY)',         color:'amo'     },
        { x:270,  y:45,  w:235, h:415, label:'ACTUATOR',                color:'esd'     },
        { x:540,  y:30,  w:220, h:465, label:'POSITIONER & PHỤ KIỆN',   color:'urea'    },
        { x:805,  y:45,  w:225, h:340, label:'FAIL-SAFE',               color:'granule' },
        { x:1065, y:130, w:255, h:160, label:'CONTROL LOOP',            color:'mid'     },
      ],
      legend: [
        { label:'Thân van (Body)',          color:'#0891b2' },
        { label:'Actuator',                 color:'#dc2626' },
        { label:'Positioner & Phụ kiện',    color:'#047857' },
        { label:'Fail-safe & Kết nối',      color:'#d97706' },
      ]
    },

    /* ─── FLASHCARDS (giữ nguyên 29 câu) ─── */
    flashcards: [
      { q:'Positioner trong van điều khiển dùng để làm gì?', a:'Để điều chỉnh vị trí van cho chính xác. Positioner hoạt động như bộ điều khiển PID thứ 2: vị trí van là PV, tín hiệu DCS là SP, áp khí đến actuator là MV.', cat:'pos' },
      { q:'Sự khác nhau giữa van 2 ngả và van 3 ngả là gì?', a:'Van 2 ngả: khống chế/điều tiết dòng lưu chất (on-off hoặc throttling). Van 3 ngả: trộn 2 dòng lưu chất hoặc chuyển hướng dòng lưu chất.', cat:'body' },
      { q:'Hai yếu tố cơ bản để van điều khiển "điều khiển được" là gì?', a:'Độ chênh lệch áp suất qua van (ΔP) và lưu lượng qua van (Q). Công thức: Q = Cv × √(ΔP/SG). Áp suất giảm qua van lớn hơn → lưu lượng cao hơn.', cat:'body' },
      { q:'11 bar bằng bao nhiêu Pa và PSI?', a:'11 bar = 1.100.000 Pa = 159,5 PSI. (1 bar = 100.000 Pa = 14,504 PSI; 11 × 14,504 = 159,5 PSI)', cat:'act' },
      { q:'Áp suất rơi trên van và lưu lượng qua van có mối quan hệ thế nào?', a:'ΔP trên van CÀNG LỚN → lưu lượng qua van CÀNG LỚN (Q = Cv × √ΔP). Khi ΔP quá lớn xảy ra choked flow – lưu lượng không tăng thêm.', cat:'body' },
      { q:'Đặc tính lưu lượng X=fast opening, Y=linear, Z=equal percentage: đặc điểm từng loại?', a:'Fast-opening (X): mở nhỏ đã cho lưu lượng lớn (25%→~80% max) – dùng on-off.\nLinear (Y): lưu lượng tỷ lệ tuyến tính với độ mở – dùng áp suất ổn định.\nEqual% (Z): mỗi % hành trình tăng % Cv bằng nhau – dùng PID, áp suất thay đổi.', cat:'body' },
      { q:'Khi cần điều khiển với độ chính xác cao, thường dùng loại van nào?', a:'Van cầu (Globe valve). Có positioner, đặc tính equal% hoặc linear, rangeability 50:1. Phổ biến nhất tại NM Đạm Cà Mau, hãng Fisher.', cat:'body' },
      { q:'Nhận biết tên 3 loại van qua hình ký hiệu P&ID: globe, check, butterfly?', a:'Globe valve: ký hiệu hình tam giác/bowtie với vòng tròn. Check valve: ký hiệu có mũi tên 1 chiều. Butterfly valve: ký hiệu đĩa tròn xoay. (Theo ISA 5.1)', cat:'body' },
      { q:'Van on-off có cần positioner không? Tại sao?', a:'KHÔNG cần positioner. Van on-off chỉ cần 2 vị trí (đóng/mở hoàn toàn), không cần feedback vị trí liên tục. Positioner chỉ cần cho van ĐIỀU TIẾT.', cat:'pos' },
      { q:'Sắp xếp các chi tiết actuator diaphragm theo thứ tự từ trên xuống?', a:'(1) Diaphragm (màng). (2) Actuator spring (lò xo). (3) Spring seat (đế lò xo). (4) Actuator stem (ty actuator). (5) Stem connector (khớp nối ty). (6) Indicator scale (thước chỉ thị hành trình).', cat:'act' },
      { q:'Positioner dùng để làm gì trong van điều khiển? (Câu hỏi ôn tập lần 2)', a:'Điều chỉnh vị trí van cho chính xác bằng cách so sánh vị trí thực (PV) với tín hiệu đặt (SP) và điều chỉnh áp khí đến actuator (MV) theo nguyên lý PID thu nhỏ.', cat:'pos' },
      { q:'Sắp xếp các chi tiết van cầu từ ngoài vào trong: Packing, bonnet, body, plug, seat?', a:'(1) Packing. (2) Bonnet. (3) Body. (4) Plug. (5) Seat. Trim = Plug + Seat + Cage.', cat:'body' },
      { q:'Actuator màng lò xo DA (stem xuống khi cấp khí) kết hợp body ATO → đây là loại van nào?', a:'Fail Close (FC). Khi mất khí: lò xo đẩy stem lên → ATO → van mở... Sai! Đúng là DA+ATO=FC: mất khí → lò xo đẩy stem ngược (lên), với ATO thì lên=đóng → FC.', cat:'fs' },
      { q:'Actuator màng lò xo DA kết hợp body ATC → đây là loại van nào?', a:'Fail Open (FO). DA + ATC = FO: mất khí → lò xo đẩy stem lên → ATC (stem lên = mở) → van mở khi mất khí = FO.', cat:'fs' },
      { q:'Positioner pneumatic + bộ điều khiển xuất tín hiệu điện 4-20mA → cần thêm thiết bị gì?', a:'Cần I/P Converter. I/P nhận 4-20mA DC → xuất 3-15 psi cho positioner pneumatic. Ký hiệu: FY trên P&ID.', cat:'pos' },
      { q:'Có bao nhiêu loại positioner (bộ định vị van)? Kể tên.', a:'3 loại: (1) Pneumatic: in 3-15 psi → out 3-15 psi. (2) Analog I/P: in 4-20mA → out 3-15 psi. (3) Smart/Digital: HART, Foundation Fieldbus hoặc Profibus PA.', cat:'pos' },
      { q:'Thiết bị nào dùng để điều chỉnh áp suất nguồn khí cho phù hợp bench set của actuator?', a:'Bộ điều áp – Pressure Regulator (Fisher 67D/67C). Điều chỉnh áp nguồn khí cấp vào actuator/positioner đúng giá trị bench set.', cat:'pos' },
      { q:'Regulator lắp đặt trên thân van dùng để làm gì?', a:'Cài đặt áp suất cấp vào actuator đúng theo giá trị bench set cho phép. Bench set là khoảng áp để đóng/mở hoàn toàn van (VD: 3-13 psi, 5-15 psi).', cat:'pos' },
      { q:'Thiết bị nào giữ khí nén trong actuator làm cho van giữ nguyên vị trí khi mất khí?', a:'Lock-up Valve. Khi mất áp nguồn khí: lock-up valve cô lập/khóa khí trong actuator → van không thay đổi vị trí = Fail Last (FL).', cat:'pos' },
      { q:'Travel (hành trình) van 3,5 inch bằng bao nhiêu mm?', a:'3,5 inch × 25,4 mm/inch = 88,9 mm ≈ 89 mm.', cat:'act' },
      { q:'Travel (hành trình) van 1,5 inch bằng bao nhiêu mm?', a:'1,5 inch × 25,4 mm/inch = 38,1 mm ≈ 38 mm.', cat:'act' },
      { q:'Đồng hồ áp suất đầu vào positioner DVC6010S có phạm vi 0-4 bar. Chọn đồng hồ psi thay thế?', a:'4 bar × 14,504 = 58 psi → chọn đồng hồ 0-60 psi (phù hợp nhất, bao phủ được 58 psi).', cat:'pos' },
      { q:'Positioner dùng tín hiệu điều khiển khí nén 3-15 psi là loại positioner nào?', a:'Bộ định vị khí nén (Pneumatic Positioner). Tín hiệu vào 3-15 psi khí nén → ra 3-15 psi. Cổ điển, cần I/P trước nó nếu DCS xuất 4-20mA. Fisher 3582.', cat:'pos' },
      { q:'Hệ số Cv của van là gì? Công thức tính Cv?', a:'Cv = số GPM nước (60°F) chảy qua van mở hoàn toàn với ΔP = 1 psi. Công thức: Cv = Q × √(SG/ΔP) với Q (GPM), SG (tỷ trọng), ΔP (psi).', cat:'body' },
      { q:'Lực tác động lên valve stem: diện tích màng 200 mm², áp suất 15 psi. Tính lực F?', a:'F = A × P = 200×10⁻⁶ m² × (15 × 6894 N/m²) = 0,0002 × 103.410 = 20,682 N. (1 psi = 6.894 Pa)', cat:'act' },
      { q:'Bench set là gì? Tại sao là thông số quan trọng nhất của actuator?', a:'Bench set = khoảng áp suất khí tác động lên màng để van đi từ mở hoàn toàn đến đóng hoàn toàn (không gắn body). VD: DA 3-13 psi, RA 5-15 psi. Quan trọng vì xác định phạm vi điều tiết và tuning của positioner.', cat:'act' },
      { q:'Dead band của van điều khiển là gì? Nguyên nhân?', a:'Dead band = khoảng hành trình van KHÔNG thay đổi khi áp suất màng thay đổi. Nguyên nhân: ma sát packing & seal. Biểu thị bằng % span. Positioner giúp giảm dead band (kín vòng lặp vị trí).', cat:'act' },
      { q:'Trip valve 377 (Fisher) là gì? Khác air relay thế nào?', a:'Trip valve 377 = tích hợp 2 air relay trong 1 thiết bị. Dùng cho piston double acting. 3 chế độ: FC (bình tích áp 1 ngõ), FL (bịt kín 2 ngõ C&F), FO (đảo C&F). Air relay đơn chỉ có 1 bộ, 3 ngõ.', cat:'fs' },
      { q:'Actuator Rack & Pinion: Single acting vs Double acting – fail-safe khác nhau thế nào?', a:'Single acting: 1 phía khí nén + lò xo → fail-safe tự nhiên (FC hoặc FO khi mất khí). Double acting: 2 phía khí nén → lực lớn hơn NHƯNG không fail-safe tự nhiên → cần trip valve 377 hoặc lock-up valve.', cat:'act' },
    ]
  },
"""

with open('C:/Users/PHUOC VINH/PVCFC-KNL/other-skills.js', 'w', encoding='utf-8') as f:
    f.write(prefix + NEW_VAN + suffix)
print('Done. Van skill updated with cells[] + concepts{}.')
